### ISSUE TITLE
Conduct a user pilot sample link broken

### ISSUE THREAD

**Issue by mcantin** [MicrosoftDocs/Viva#259]
https://docs.microsoft.com/en-us/viva/insights/personal/briefing/be-pilot?source=docs#design-your-test-plan-and-feedback-survey

Link currently is: https://download.microsoft.com/download/a/9/f/a9fea3f4-77a9-4465-a6eb-c021087c3b7f/fedback-survey.docx

Should be: https://download.microsoft.com/download/a/9/f/a9fea3f4-77a9-4465-a6eb-c021087c3b7f/feedback-survey.docx

(Notice the second 'e' in feedback)

**Comment by tiburd** [comment]
Thank you for reporting this. It appears the link works correctly now.
