### ISSUE TITLE
Please update the names for the Business plans

### ISSUE THREAD

**Issue by gabsto-ms** [MicrosoftDocs/Viva#270]
Hello,

Please update the **Business**  plans according to their current names:

Insights by MyAnalytics - Microsoft 365 E3, **Microsoft 365 Business**, Microsoft 365 A3 for faculty and students, Office 365 E3, Office 365 E1, Office 365 A3 for faculty and students, Office 365 E3 Developer, Office 365 G3, **Business Premium**, and **Business Essentials**”

You can find the current names here:
https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products

Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4d68f-17e0-d538-6095-70f44e214bbf
* Version Independent ID: 2149a913-8877-fff0-5b08-050fb5adbbde
* Content: [Plans and environments for personal insights](https://docs.microsoft.com/en-us/viva/insights/personal/overview/plans-environments)
* Content Source: [Viva/insights/personal/Overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Overview/plans-environments.md)
* Product: **mya**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by lindspea** [comment]
@gabsto-ms thank you for reaching out and helping to improve Microsoft Docs. I've just checked the article and it seems that it's been updated in the interim. Please let me know.

**Comment by gabsto-ms** [comment]
Hi,

Yes, it is ok now.

Thanks,
Gabi

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
