### ISSUE TITLE
Ambiguity on data used for Group Insights

### ISSUE THREAD

**Issue by martinctc** [MicrosoftDocs/Viva#273]
Hi team, would like to submit a feedback on the following line:

_The admin uses the organizational data that is uploaded into Viva Insights in Workplace Analytics or that’s presented in Azure AD._

There is no further information or links on how an admin knows / decides whether the organizational data or the Azure AD data is being used. This is critical because some organizations may have outdated Azure AD data and will need to know where to direct resources on maintaining - whether it be the organizational data or Azure AD. 

If more information, or a link to a relevant documentation can be provided, that would be very helpful. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423f9c9a-646c-b1b0-5b4c-8d037046d16d
* Version Independent ID: 423f9c9a-646c-b1b0-5b4c-8d037046d16d
* Content: [Explore group insights in Viva Insights](https://docs.microsoft.com/en-us/viva/insights/use/myteam-explore)
* Content Source: [Viva/insights/Use/myteam-explore.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/myteam-explore.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @martinctc, thank you for your feedback.

You can find more information in the following article:
https://docs.microsoft.com/viva/insights/use/organizational-data

**Comment by tiburd** [comment]
Closing because this article has been deleted. 
Redirect points to: 
https://github.com/MicrosoftDocs/Viva/blob/public/Viva/insights/org-team-insights/team-insights.md.
