### ISSUE TITLE
Get-SPOIsCommSite is not available

### ISSUE THREAD

**Issue by ValerianHts** [MicrosoftDocs/Viva#278]
**Get-SPOIsCommSite** : The term 'Get-SPOIsCommSite' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

(Get-Module Microsoft.Online.SharePoint.PowerShell).Version

_Major  Minor  Build  Revision
-----  -----  -----  --------
16     0      8316   0_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad2452fb-b5a4-8d84-d7b8-e6c890423c84
* Version Independent ID: ad2452fb-b5a4-8d84-d7b8-e6c890423c84
* Content: [Add the Viva Topics app in the Teams Admin Center](https://docs.microsoft.com/en-us/viva/topics/add-topics-app)
* Content Source: [Viva/topics/add-topics-app.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/add-topics-app.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by lindspea** [comment]
@ValerianHts thank you for pointing this out and helping to improve Microsoft Docs. Just for clarity, is this related to the article you referenced, as I can't seem to find it here.

**Comment by scanum** [comment]
Closing this due to no response
