### ISSUE TITLE
You forgot the most important bit of information...where/how to get it

### ISSUE THREAD

**Issue by THERockyH** [MicrosoftDocs/Viva#279]
You have this whole page about The Viva Insights Outlook Add-In, but you skip right to why you can't see it, and computer settings. How about starting with how to install it? Or is it so bad that you automatically know people will have problems, so you just skip to the troubleshooting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ad0de9-1db2-4180-3863-a59c8b0ae030
* Version Independent ID: e87a0970-fa67-3cce-c885-cde6c6246e33
* Content: [About Viva Insights Outlook add-in](https://docs.microsoft.com/en-us/viva/insights/personal/Use/add-in)
* Content Source: [Viva/insights/personal/Use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/add-in.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @THERockyH, thank you for your feedback.

I can see the following sentence in the article:
"The admin enables the add-in by default in the Exchange admin center. If your admin sets the deployment status as "Optionally, disabled by default," you can manually add the Viva Insights Outlook add-in yourself from the Microsoft Store Add-ins."

Do you think that's not enough?

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
