### ISSUE TITLE
Support Multiple Vacations

### ISSUE THREAD

**Issue by infoseek1** [MicrosoftDocs/Viva#280]
[Enter feedback here]
Can this support multiple vacations,  For example I'm taking 3 days off next week and in two months taking 2 weeks off. 

Also can you add to documentation, how does Viva detect that you are taking vacation for reminders?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6dc2abc-1934-5e32-ed0e-ced7d791375d
* Version Independent ID: aac13096-8345-abd2-4da5-5e73acd464de
* Content: [Use Microsoft Viva Insights in Outlook](https://docs.microsoft.com/en-us/viva/insights/personal/use/use-the-insights#plan-your-time-away)
* Content Source: [Viva/insights/personal/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/use-the-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by lindspea** [comment]
@infoseek1 thank you for reaching out and helping to improve Microsoft Docs. Does it not give you an option to add more than one time out of office'?  I'll investigate further.

**Comment by infoseek1** [comment]
I have not seen a method to have Viva insights detect this and go through the well designed steps in Insights for vacation planning.  Is there a trigger word/ method in Outlook that detects vacation schedule, I'm unsure how Viva insights algorithm detects vacation. Thanks for investigating.

**Comment by lindspea** [comment]
@infoseek1 thanks for letting me know. Let me investigate further.

**Comment by lindspea** [comment]
@infoseek1 please let me know if this article helps at all - https://docs.microsoft.com/viva/insights/personal/overview/mya-faq. I also noticed that the document in question has been updated with more information as well. Please can you let me know if you require more information. Thanks so much.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
