### ISSUE TITLE
Viva insights lunch hour

### ISSUE THREAD

**Issue by ndsheela** [MicrosoftDocs/Viva#288]
https://docs.microsoft.com/en-us/viva/insights/personal/use/use-the-insights#set-lunch-hours
Where is the settings/feature mentioned in this article?  its surprising that Microsoft does not update documentation on its own products

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6dc2abc-1934-5e32-ed0e-ced7d791375d
* Version Independent ID: aac13096-8345-abd2-4da5-5e73acd464de
* Content: [Use Microsoft Viva Insights in Outlook](https://docs.microsoft.com/en-us/viva/insights/personal/use/use-the-insights#set-lunch-hours)
* Content Source: [Viva/insights/personal/Use/use-the-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/use-the-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Hello @ndsheela how are you? hope you are doing great
I am sorry, I am having some trouble understanding, can you kindly detail what do you see is missing from the article?
Thank you

**Comment by ndsheela** [comment]
Hi,

It's not something in the article, lunch hours mentioned in the article
does not exist anymore in the site

**Comment by get-itips** [comment]
> Hi, It's not something in the article, lunch hours mentioned in the article does not exist anymore in the site
> […](#)

Hello @ndsheela thanks for clarifying, the article is talking about the integration between Viva insights and Outlook.
The option to set lunch hours is in the Outlook Add-in for Viva Insights.

Let me know if I understood you correctly,

**Comment by get-itips** [comment]
@scanum
