### ISSUE TITLE
Custom VIVA Learning content is not displayed in the VIVA Learning Interface 

### ISSUE THREAD

**Issue by MarvinBoehm** [MicrosoftDocs/Viva#289]
Dear Microsoft Team,

we recently started working with Viva Learning and when trying to configure SharePoint as a content source we encountered the following problem:

- Add URLs to SharePoint Repository List
According to the info site after creating a SharePoint List one has to populate it with the URLs to the learning content folder. The screenshots show a site content URL added to the learning content folder but when the repository page is updated the URL under “Folder URL” is a folder and not a side content URL.
Our question is which URL has to be added? A folder or site content URL?

- In the info site the step by step guide can be misleading since there are different document libraries used (Learning, Learning Test, Learn – Design, Learning Development) to show the different steps that need to be done in order to set up SharePoint as a content source.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by SebastianTura19** [comment]
Hi,

I have the same problem in a DEMO Env and also a MSFT Partner I am working with. Basically, once I close the own SPO Library, in the Viva Learning platform it's not shown. It might be a bug or something that maybe the prod team can check?
I`m aware that this is not related to the documentation available in DOCS but maybe you can get in touch with prod team.

Thank you!
