### ISSUE TITLE
datafactory_odata_arm_template link not working

### ISSUE THREAD

**Issue by Snubsly** [MicrosoftDocs/Viva#290]
Hi the link to the datafactory_odata_arm_template does not work

https://vscomporgsa.blob.core.windows.net/files/DataFactory_OData_arm_template.zip?sp=r&st=2021-11-23T16:55:42Z&se=2022-06-01T23:55:42Z&spr=https&sv=2020-08-04&sr=b&sig=hAmyCMD1R4UARcrWTxjK20Yflo9ZQmXWkCeNqtXfqpk%3D

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab6e89d-a77c-9361-45a4-bfbf9fa49a31
* Version Independent ID: bab6e89d-a77c-9361-45a4-bfbf9fa49a31
* Content: [Complex organizations and Viva Insights](https://docs.microsoft.com/en-us/viva/solutions/complex-organization-insights)
* Content Source: [Viva/solutions/complex-organization-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/solutions/complex-organization-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-smandalika**

**Comment by lindspea** [comment]
@Snubsly thank you for pointing this out and helping to improve Microsoft Docs. Is this the correct link - https://docs.microsoft.com/azure/data-factory/quickstart-create-data-factory-resource-manager-template?msclkid=8edf9bbeaaad11ec886f95309aa71cf4

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
