### ISSUE TITLE
Automated Focus Time - how to cancel it?

### ISSUE THREAD

**Issue by LynetteWhite** [MicrosoftDocs/Viva#291]
Hello

I signed up for automated scheduling of focus time whilst it was under the My Analytics banner before it moved to Viva. How do I get back to those settings to change or in fact to cancel it to appease my boss!? There is no mention of the automatic feature in the new MS Viva Insights as part of MS Teams.

Lynette

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
