### ISSUE TITLE
What type of SharePoint Site?

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/Viva#292]
I think it would help those new to Viva Learn to describe the type of SharePoint site that should be created e.g. should it be a Group Connected Team Site, Communication Site or a Team Site without a Microsoft Group etc.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://docs.microsoft.com/en-gb/viva/learning/configure-sharepoint-content-source#learning-service)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by dariomws** [comment]
Hi @buildbod, thank you for your feedback.

I think there is no need to specify that as it could be any site type. I have tried to create the repository in a Teams site and Communication site successfully.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
