### ISSUE TITLE
Able to edit category for focus time

### ISSUE THREAD

**Issue by sumotutu** [MicrosoftDocs/Viva#293]
Not able to change the category of focus time once they are set up in calendar. Would be great to be able to customize in viva before they are set up.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
