### ISSUE TITLE
Need licensing clarity around Viva Insights

### ISSUE THREAD

**Issue by JAndre7** [MicrosoftDocs/Viva#294]
Hello. This page has led to customer confusion, so I'd like to ask that it be more specific about a few aspects. The top section of the page listing 4 options is incomplete and confusing. Part of the challenge is due to customers being able to use a set of Viva Insights with solely an Office/Microsoft 365 E3 SKU. 

1) The use of Viva Insights with only an E3 SKU is not listed in this set of 4 items. It needs to be in order to be complete and less confusing
2) It took me quite a while to figure out that the text after the dash after each bullet listed the prerequisite for having that SKU. Can you please make it clear that what you are listing is a prerequisite? The confusion otherwise starts (a) by reading the first bullet and interpreting it as saying that the following SKU INCLUDE Viva insights (as we know features of Viva Insights are included). Then it gets increasingly confusing when looking at the second bullet because nowhere is there a definition of MyAnalytics (Full) - so one just stops and thinks one is correct for the first bullet - but that's wrong as I described it
3) Then, there should be a clear page of functionality that one gets with each licensing type ... (a) whatever you get with and E3 suite, (b) what you get with a purchased Viva Insights SKU, (c) what you get with a MyAnalytics (Full) SKU, etc. ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4d68f-17e0-d538-6095-70f44e214bbf
* Version Independent ID: 2149a913-8877-fff0-5b08-050fb5adbbde
* Content: [Plans and environments for personal insights](https://docs.microsoft.com/en-us/viva/insights/personal/overview/plans-environments)
* Content Source: [Viva/insights/personal/Overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Overview/plans-environments.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @JAndre7, thank you for your feedback.

There were several updates on the article in April. To answer your items:

1. I can see E3 included in the article for Viva Insights:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/33589238/165628262-9a2488d9-dfbb-4f81-b2da-ca6f476ff72b.png">

2. and 3. The article includes the Microsoft 365 or Office 365 plans that have available/included each Viva Insight service plan. I couldn't find an article with a detailed description of Viva Insights, MyAnalytics (Full) and Insights by MyAnalytics. This is the best one I can find:
https://docs.microsoft.com/office365/servicedescriptions/mya-service-description
But as you can see, they are included with Viva Insights now.

@madehmer, maybe you can provide additional information here. Thanks!

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
