### ISSUE TITLE
SP app bar 'screen estate'

### ISSUE THREAD

**Issue by Harmve** [MicrosoftDocs/Viva#295]
The SP app bar is a fixed bar on the left hand side taking some screen estate especially affecting the full width communication site home pages. Are there any plans to make this bar configurable of how and where to appear? 

For instance could it be moved to the top SP bar instead or could it be made only to appear as an 'over-lay' when hovering over the 'App launcher' in the top left hand corner (a bit similar to the mobile Android experience)?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
