### ISSUE TITLE
Insights: I full screened it and then couldn't return to TEAMS

### ISSUE THREAD

**Issue by LisaJo48** [MicrosoftDocs/Viva#298]
I full screen the meditation and then there was no manner by which to close Viva Insights and return to my list of teams and chats in TEAMS. I had to Quit TEAMS altogether in order to get the menu on the left to appear so that I could navigate away from the meditation  to something else.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
