### ISSUE TITLE
Incorrect title for Japanese article

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/Viva#299]
Hello Team,

This is for Viva learning, but the title is Viva Topic (Viva トピック).

![image](https://user-images.githubusercontent.com/13634805/164884415-d1613e43-297e-4c9f-a011-d7915e1509b0.png)

Can you please correct it to Viva Learning (Viva ラーニング) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe755235-c542-395d-4958-cf5ad3e86a32
* Version Independent ID: fe755235-c542-395d-4958-cf5ad3e86a32
* Content: [Introduction to Microsoft Viva Learning](https://docs.microsoft.com/en-us/viva/learning/?source=docs)
* Content Source: [Viva/learning/index.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/index.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by cdowling1971** [comment]
Hi @kefujino 

Thanks for reporting this problem, I have logged an internal case/ticket, and we will continue to follow up internally to make this fix.

FYI @TinaMcN @scanum

**Comment by cdowling1971** [comment]
Hi @kefujino the issue you reported is now fixed, thanks for your review correction.

Regards,
Clair
