### ISSUE TITLE
Yammer misspelt

### ISSUE THREAD

**Issue by DarrellaaS** [MicrosoftDocs/Viva#302]
In the section "Where does content in the feed come from?"
https://docs.microsoft.com/en-us/viva/connections/faqs-viva-connections-feed#question-where-does-content-in-the-feed-come-from

Yammer is misspelt as "Yammar". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23114d5-dc01-a971-c612-67204069a677
* Version Independent ID: d23114d5-dc01-a971-c612-67204069a677
* Content: [Frequently asked questions about the Feed for Viva Connections](https://docs.microsoft.com/en-us/viva/connections/faqs-viva-connections-feed)
* Content Source: [Viva/connections/faqs-viva-connections-feed.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/faqs-viva-connections-feed.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by lindspea** [comment]
@scanum this can be closed thank you.
