### ISSUE TITLE
Ability to exclude emails from Cortana

### ISSUE THREAD

**Issue by BenyH5** [MicrosoftDocs/Viva#303]
Hi,

In general, Viva/Cortana are doing a good job in the daily briefing email.
However some tasks are created based on emails sent to a distribution list, or generated by automatic emails.
In such case, the tasks are not useful.
For example, i am receiving emails from Gitlab Merge Requests sent to a group ending by "Please review" and Cortana list it as a task.
I think it can be a good improvement to have an option to exclude emails (based on Sender/To/Rules) from Cortana analysis

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
