### ISSUE TITLE
The steps to create a Video News Link to be shown in the Feed for Viva Connections don't work

### ISSUE THREAD

**Issue by jojocode77** [MicrosoftDocs/Viva#304]
When attempting to get content from Stream to appear in the Feed for Viva Connections web part in SharePoint Online, I:

1. Read the [following article](https://docs.microsoft.com/en-us/viva/connections/faqs-viva-connections-feed#question-what-can-i-expect-to-see-in-the-feed), specifically the section "3. Videos in SharePoint hosted by Stream"
2. Read the [following article](https://docs.microsoft.com/en-us/viva/connections/viva-connections-overview#viva-connections-feed), specifically the section "Feed content sources - Stream (build on SharePoint)
3. Read the [following article](https://docs.microsoft.com/en-us/viva/connections/video-news-links) and followed all the steps.

I have uploaded a video in to SharePoint, created a sharing link and used that link as a Video News Link. I have waited over an hour, but the video does not appear in the Feed for Viva Connections web part, nor in the Feed tab in the Teams mobile app.

I have uploaded a video to my OneDrive, created a sharing link and used that link as a Video News Link. The link would not be accepted as valid.

Neither of the sharing links created were using the microsoftstream.com domain shown in the third article linked above.

In the second article linked above, under "Feed content sources", it states "Video in a news post". I have also tried uploading a video within a normal news post. The video does not appear in the Feed.

In the third article linked above, it mentions under "Options for publishing Video news links" "Boost the video to promote in within the Viva Connections feed" - there is no Boost button.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
