### ISSUE TITLE
Viva Insights - Inspiration Library - Read/Unread

### ISSUE THREAD

**Issue by josuave** [MicrosoftDocs/Viva#305]
There is no current way to mark an inspiration library item as unread. There is no mouseover, or any other discoverable detail, on the little eye symbol that represents read/unread. This causes the user of the feature to either ignore the symbol or to click the symbol. This immediately changes the item to read and changes the item's position in the collection. This is a little cumbersome as a first-time experience as the user may not have wanted to view it or may discover, while getting into it, that the item is not appropriate for themselves at that time. It would be beneficial to reset the state of an item in either scenario.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
