### ISSUE TITLE
Could you tell me all Viva Insights metric for graph API?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#308]
[Enter feedback here]

Hi team.

I want know about all Viva Insights metric for graph API. Is this information published on docs now?  Our partner want to konow about more detail Viva Insights metric that they can get.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75bc23-75ef-8ce6-74ce-a0166cd79190
* Version Independent ID: c9d7a8a3-8b13-80f2-5755-049fb98badcf
* Content: [Advanced insights in Viva Insights](https://docs.microsoft.com/en-us/viva/insights/overview/get-started?msclkid=e4656860d0c111ec9ab375e9c21bce7e)
* Content Source: [Viva/insights/Overview/Get-started.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Overview/Get-started.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
