### ISSUE TITLE
Clarification Needed: ManagerID for top leader?

### ISSUE THREAD

**Issue by sparkitect** [MicrosoftDocs/Viva#309]
Everything seems to indicate that ManagerID is required for each row in the .csv but what are we supposed to put there for the top leader of the org (Layer=0) who doesn't have a manager?

Are we not supposed to include top leaders in our upload?

I'm going to try putting their own email as their managerID and see what happens...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2cbe9fb-bfe5-0d6d-7e61-f2617fc857a9
* Version Independent ID: 00a01a69-28a4-56cb-e0a8-3b57c1cbfe99
* Content: [Prepare organizational data for Viva Insights](https://docs.microsoft.com/en-us/viva/insights/setup/prepare-organizational-data)
* Content Source: [Viva/insights/Setup/Prepare-organizational-data.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Setup/Prepare-organizational-data.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
