### ISSUE TITLE
Trial duration: 90 days or 60 days?

### ISSUE THREAD

**Issue by jmuehlenbein** [MicrosoftDocs/Viva#310]
Hello, I followed the instructions to enable the Viva Topics trial in our tenant but it says the trial period is only for 60 days, not 90 days as stated in the article. Just wondering which is 'correct'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b1c3da-7939-8d93-0ddd-77b88bf375aa
* Version Independent ID: 33b1c3da-7939-8d93-0ddd-77b88bf375aa
* Content: [Run a trial of Microsoft Viva Topics](https://docs.microsoft.com/en-us/viva/topics/trial-topics?source=docs)
* Content Source: [Viva/topics/trial-topics.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/trial-topics.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @ruthholls
* Microsoft Alias: **ruthhollands**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by jmuehlenbein** [comment]
Typical Microsoft. I let you know there's an issue and somehow it becomes my problem to fix. Thanks for...um...nothing.
