### ISSUE TITLE
The commands Set-UserAnalyticsConfig and Get-UserAnalyticsConfig are depreciated.

### ISSUE THREAD

**Issue by Kressmark** [MicrosoftDocs/Viva#311]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 412cc99c-71d3-b2ad-f2e6-38b6270522ed
* Version Independent ID: adf90afb-7fe5-9c46-0992-e030b8b995e1
* Content: [Personal insights deployment guide](https://docs.microsoft.com/en-us/viva/insights/personal/setup/deployment-guide)
* Content Source: [Viva/insights/personal/Setup/deployment-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Setup/deployment-guide.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
