### ISSUE TITLE
The information about the admin dashboard is not clear. A picture would be helpful. Which "panel" do you reference when speaking about the admin experience in this sentence "To access the Viva Goals Admin Dashboard, navigate toward the bottom of the left side panel and select “Admin” next to the gear icon."

### ISSUE THREAD

**Issue by mfulan** [MicrosoftDocs/Viva#312]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5be45c-c23d-3c60-b0cd-1a12669d8e72
* Version Independent ID: 2d5be45c-c23d-3c60-b0cd-1a12669d8e72
* Content: [Navigate the admin dashboard](https://docs.microsoft.com/en-us/viva/goals/navigate-admin-dashboard#how-to-access-the-admin-dashboard-and-what-to-do-there)
* Content Source: [Viva/goals/navigate-admin-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/navigate-admin-dashboard.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ms-vikashkoushik
* Microsoft Alias: **vsreenivasan**

**Comment by get-itips** [comment]
Hello, thanks for your feedback, I am looking into this
