### ISSUE TITLE
If using Sharepoint as a content source, does it need to be a modern site?

### ISSUE THREAD

**Issue by katou0503** [MicrosoftDocs/Viva#314]
[Enter feedback here]
There are no restrictions stated, but it seems that content cannot be linked to VL on the Classic site.
Is this a product specification (limitation)?
If it is a specification (limitation), please specify on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://docs.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by get-itips** [comment]
Hello @katou0503 sorry for the delay, I am looking to confirm this

**Comment by get-itips** [comment]
Hello @katou0503 
I set up a classic site as a source and the list *Learning App Content Repository* was created, did that happen for you? I am still waiting for the content to show up in VL.
Thanks

**Comment by get-itips** [comment]
Hello @katou0503 Could you see my last comment? Thanks

**Comment by get-itips** [comment]
@katou0503 could you see my comment here? thanks

**Comment by get-itips** [comment]
@scanum
