### ISSUE TITLE
Admins do not have ”Full access" in Analyst settings.

### ISSUE THREAD

**Issue by takataka365** [MicrosoftDocs/Viva#316]
Analyst settings include the following four settings

- system defaults
- privacy settings
- Meeting exclusion
- Attendee exclusion

The docs table says that the Admin has full access to Analyst settings, but I verified in my environment that the Admin has access to system defaults and Privacy settings, but not Meeting exclusion and Attendee exclusion. 
Therefore, the docs statement may be misleading.

Also, is the following sentence listed before the table incorrect?
"Admins and Analysts can access and customize meeting and attendee exclusion rules that help ensure data accuracy."
I think the following statement is correct.
"Analysts can access and customize meeting and attendee exclusion rules that help ensure data accuracy."

I would appreciate it if you could confirm this.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d94b9cb-f076-35d6-c25e-2147c9059552
* Version Independent ID: 72011660-6f91-cb3b-05e3-30657401aba1
* Content: [Advanced insights Controls](https://docs.microsoft.com/en-us/viva/insights/Use/Settings)
* Content Source: [Viva/insights/Use/Settings.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/Settings.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Hello @takataka365 I am looking into this

**Comment by get-itips** [comment]
Article has been updated. Thanks!
