### ISSUE TITLE
Wildcard characters not allowed

### ISSUE THREAD

**Issue by tnewton1** [MicrosoftDocs/Viva#318]
On this page, you're prompted to run `Install-Module *AzureAD*` which causes PowerShell to kick back: `Install-Module: The specified name '*AzureAD*' should not contain any wildcard characters, please correct it and try again.` Not sure if this is a formatting error but after searching around, it seems the right command might be `Install-Module AzureAD`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bcb13b7-4740-e612-b4e4-098eedbaa11a
* Version Independent ID: be670997-31f2-996f-3ef5-d477d5791477
* Content: [Assigning licenses with PowerShell](https://docs.microsoft.com/en-us/viva/insights/use/assigning-licenses-with-powershell)
* Content Source: [Viva/insights/Use/Assigning-licenses-with-powershell.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/Assigning-licenses-with-powershell.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Thanks for your feedback!
