### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/Viva#319]
This note doesn't make sense:

_Only the Microsoft 365 Groups permissions apply. Viva Learning doesn't support user- or SharePoint-based permissions. Viva Learning won't ingest files that don't have associated Microsoft 365 Groups `permissions._

What does this mean by SharePoint based permissions. ALL permissions in SharePoint are SharePoint based permissions.
It then goes on to say:

_While only Microsoft 365 (recommended) and Mail-enabled security group types are supported, it is recommended that you use Microsoft 365 (recommended)._

So which one is it? Is it saying that you can only use content from M365 group connected sites? Or can it be from any site?

It certainly can't mean that you have to use M365 groups to control permissions. That would be a terrible design for company-wide or dept wide training resources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://docs.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source?view=o365-worldwide)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
