### ISSUE TITLE
Formatting issue in Microsoft Viva Insights API documentation

### ISSUE THREAD

**Issue by Jamesargy6** [MicrosoftDocs/Viva#323]
The `egressDecryptionKey` URI does not display correctly on the documentation page, probably because of an errant newline [here](https://github.com/MicrosoftDocs/Viva/blob/public/Viva/insights/advanced/analyst/api.md?plain=1#L40)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a9d80b-082c-86f0-ed75-fec4b59c9b79
* Version Independent ID: 67a9d80b-082c-86f0-ed75-fec4b59c9b79
* Content: [Microsoft Viva Insights API](https://docs.microsoft.com/en-us/viva/insights/advanced/analyst/api)
* Content Source: [Viva/insights/advanced/analyst/api.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/analyst/api.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Looks like the URI now displays correctly, can you confirm? Thanks

**Comment by get-itips** [comment]
@scanum
