### ISSUE TITLE
Add "Insights by MyAnalytics" as a requirement, rather than "Applicable Service Plan"

### ISSUE THREAD

**Issue by SeanTGeoghegan** [MicrosoftDocs/Viva#325]
It has been found that the Viva Insights or MyAnalytics (Full) service Plan alone causes issues with certain items deploying (such as the Add-in). Customers are also confused with the licensing thinking that a Viva Insights license alone is acceptable to provide full functionality of Viva, when it is just the two add-on features of "Delay Delivery" and "Track email open rate inline suggestions"

Can we add confirmation to _https://docs.microsoft.com/en-us/viva/insights/personal/overview/plans-environments#access-to-viva-insights-elements_ that the base features of Viva Insights require the Insights by MyAnalytics service plan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4d68f-17e0-d538-6095-70f44e214bbf
* Version Independent ID: 2149a913-8877-fff0-5b08-050fb5adbbde
* Content: [Plans and environments for personal insights](https://docs.microsoft.com/en-us/viva/insights/personal/overview/plans-environments)
* Content Source: [Viva/insights/personal/Overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Overview/plans-environments.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by SeanTGeoghegan** [comment]
To clarify - this issue only occurs if the service plan Insights by MyAnalytics is not assigned to users. Many customers will deploy minimum viable product, and remove some of these licensed features, leaving no clear boundary as to what features provide what functionality as a whole.

**Comment by get-itips** [comment]
Hello @SeanTGeoghegan  I am looking into this

**Comment by get-itips** [comment]
A redirect to another current article was set up.
Closing.
