### ISSUE TITLE
Allow notes to be added to reflections

### ISSUE THREAD

**Issue by janekvap** [MicrosoftDocs/Viva#326]
It would be good to be able to add a short note to why I had particular reflection sometimes so when looking back I can quickly find out why I put in high/low feeling to maybe discover patterns.

**Comment by scanum** [comment]
@janekvap Thanks for the feedback, could you please link the article you are referring to? Thanks

**Comment by MrWayneS** [comment]
I was going to suggest this feature be added to Viva Insights as well.  The feature is described at [https://learn.microsoft.com/en-us/viva/insights/personal/teams/reflect](url) and it would be great to optionally add a short note associated with my saved reflection about why I might have felt that way.

**Comment by MarieVPPD** [comment]
I agree, I was going to suggest the same thing.  Viva Insight 'Reflections' suggest that you "Consider reflecting on the reason behind the way you are feeling." and it would be nice to journal at that time.  Any way to add a simple note associated with that moment would be nice to have:
![image](https://user-images.githubusercontent.com/129549009/229209661-e333cf2e-4d08-4539-8711-f2c64a4ea9f7.png)

**Comment by get-itips** [comment]
Closing as this is not Docs related but a feature request.
For feedback, please follow https://feedbackportal.microsoft.com/feedback
