### ISSUE TITLE
No gear icon 

### ISSUE THREAD

**Issue by ackerman76** [MicrosoftDocs/Viva#327]
We have no gear icon on viva insights. We cannot configure anything. Help doc is out of date or missing details.

We get messages using the wrong time zone for our calendar appointments, and many other issues. I am likely to miss appointments since it tells me everything is hours later than actual in my time zone.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
