### ISSUE TITLE
Viva Topis: Unable to activate Viva Topics from Admin Center with Global Admin permission 

### ISSUE THREAD

**Issue by gretchunkim** [MicrosoftDocs/Viva#330]
I'm getting the following error message when attempted to activate Viva Topics form Adm Center:

![VivaTopics](https://user-images.githubusercontent.com/8564035/172699813-e9ffbc94-eefd-4ceb-bf2e-59a7c98781f7.PNG)

I've searched the documentation but can't locate any technical documentation for the error message.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by gretchunkim** [comment]
For documentation purpose including resolutin, won't it be better to keep the issue open and then close as it as I get resolution with the MS? Let me knwo what you think because others will benefit from this resolution as well.

**Comment by gretchunkim** [comment]
The root cause of the error message above for me was result off Viva Topics Subscription with E5 account.  

For anyone receiving a similiar error message check the following and attempt to re-run the activation (even it fails for the first time);
1. Check to see if Viva Topics subscription is enabled on your account coupled with E3/E5 subscription. 
2. Run the activation with global admin account may be necessary (to perform step 1).
3. Re-run the activation step mentioned in the documentation even if it tails at the first time.
