### ISSUE TITLE
Could you tell me about how to integrate Viva Insights data and 3rd party data.

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#331]
[Enter feedback here]
Hi, team !
Our patner want to get more rich insights, so they hava a plan about integrates Viva Insights data and 3rd party data. 
In this case, they have some problem. Preson ID is anonymus. They can't connect 3rd party data to Viva Insights data, because they does not know ID about specific person. 
In this situation, are there way that we integrates Viva Insights data and 3rd party data ?

Best regards,
Dai
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f56c506-854a-6173-6345-f02f091333e7
* Version Independent ID: cc878076-8f68-b200-e78c-97723fc34a6a
* Content: [Viva Insights Organizational data](https://docs.microsoft.com/en-us/viva/insights/use/organizational-data)
* Content Source: [Viva/insights/Use/organizational-data.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/organizational-data.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
