### ISSUE TITLE
How to find AccountName when adding ADO Connection 

### ISSUE THREAD

**Issue by EricVoll** [MicrosoftDocs/Viva#333]
Hi all, 

How can I find out what I'm supposed to enter in the Account Name field when adding an Azure DevOps Connection? I've tried all possible combinations that came to my mind.

Thanks,
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de1986ef-3b96-9706-59f7-b7c4d0b9a807
* Version Independent ID: de1986ef-3b96-9706-59f7-b7c4d0b9a807
* Content: [Azure DevOps integration](https://docs.microsoft.com/en-us/viva/goals/azure-devops-integration)
* Content Source: [Viva/goals/azure-devops-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/azure-devops-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ms-vikashkoushik
* Microsoft Alias: **vsreenivasan**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by GPetrites** [comment]
Any way you can simply post the resolution to this?  I'm running into the exact same issue.  Seems like a problem that can be solved with some simple documentation explaining what is meant by "Azure Account Name"...

Is it the DevOps Organization name?  The user's display name?  The user's login name?  Just as simple screen shot showing where the value in the existing screen shots comes from would be helpful.

**Comment by EricVoll** [comment]
We actually never managed to solve it. I think the Azure DevOps Admin has to unlock the app first, which they might not do for PPE services.
