### ISSUE TITLE
Could you tell me specific about query designer metrics "customizable" ?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#337]
[Enter feedback here]
Hi, team !
Our partner want to know extensibility about query designer. Some metric has "customizable". What does it refer to on query designer console? Could you be more specific?

Best regards,
Dai
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4929397-66a3-43c5-b0dd-8696bd02127a
* Version Independent ID: 04d71a91-f0f9-e87e-1be5-4d1dedc85c77
* Content: [Metric definitions for Advanced insights](https://docs.microsoft.com/en-us/viva/insights/use/metric-definitions#person-metrics)
* Content Source: [Viva/insights/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/Metric-definitions.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dshimogawa** [comment]
Please allow me to send you a gentle reminder.
I want your reply by the end of next week.

I'm afraid you are busy, but we look forward to your reply.

Thank you.

Best regards,
Daishi

**Comment by dshimogawa** [comment]
Please allow me to send you a gentle reminder.
I want your reply by the end of this week.

I'm afraid you are busy, but we look forward to your reply.

Thank you.

Best regards,
Daishi

**Comment by dshimogawa** [comment]
Please allow me to send you a reminder.
I want your reply by the end of this week.

I'm afraid you are busy, but we look forward to your reply.

Thank you.

Best regards,
Daishi

**Comment by get-itips** [comment]
Hello @dshimogawa 
I think this is what you are looking for 

https://docs.microsoft.com/en-us/viva/insights/tutorials/customize-a-metric

**Comment by get-itips** [comment]
@scanum
