### ISSUE TITLE
How to become content provider for Viva

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [MicrosoftDocs/Viva#342]
The documentation is not clear about how any training company to become a content provider for Viva just like Coursera and Edx. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a43718f-7587-8b98-10fe-07dbbfda8ffe
* Version Independent ID: 1a43718f-7587-8b98-10fe-07dbbfda8ffe
* Content: [Overview of Microsoft Viva Learning](https://docs.microsoft.com/en-us/viva/learning/overview-viva-learning?view=o365-worldwide)
* Content Source: [Viva/learning/overview-viva-learning.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/overview-viva-learning.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by get-itips** [comment]
Hello @sanjaydatasciencedojo Sanjay,
I am looking into this.

**Comment by sanjaydatasciencedojo** [comment]
Thank you Andres.

**Comment by sanjaydatasciencedojo** [comment]
Hi Andres ( @get-itips ), do you have any updates to share?

**Comment by get-itips** [comment]
Please see this recent announcement

https://techcommunity.microsoft.com/t5/microsoft-viva-blog/announcing-viva-learning-content-sync-apis/ba-p/3568719

**Comment by sanjaydatasciencedojo** [comment]
Great. Thank you for sharing that helpful link.

**Comment by tiburd** [comment]
@get-itips 
Thank you for resolving. I'm removing the writer-input-required label that I had added and closing this issue.

cc: @scanum
