### ISSUE TITLE
Power BI free user can connect workplace analytics result data from Power BI desktop?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#344]
[Enter feedback here]

Hi, Team.
In the following ricense cases, specification about Viva Insights?

[Case]
・Administrator has Power BI Pro.
・Analyst has Power BI free.
・Administrator make Viva Insights Report of Power BI template. 

[Question]
1. Analyst can connect workplace analytics result data from Power BI desktop?
2. Analyst can connect workplace analytics result data from Power BI WEB?
3. If administrator has only Power BI free, they can publish Viva Insights data (Power BI template) ?

Best regards,
Daishi.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f413821-9f08-7bac-9756-e1f91e208c3e
* Version Independent ID: fcb0e4cd-5d16-174d-d8f6-87c5584d83b6
* Content: [In-depth insights in Power BI](https://docs.microsoft.com/en-us/viva/insights/tutorials/pbi-home-deeper)
* Content Source: [Viva/insights/Tutorials/pbi-home-deeper.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Tutorials/pbi-home-deeper.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by dshimogawa** [comment]
Please allow me to send you a gentle reminder.
I want your reply by the end of this week.

I'm afraid you are busy, but we look forward to your reply.

Thank you.

Best regards,
Daishi

**Comment by dariomws** [comment]
Hi @dshimogawa,

Here we are limited to documentation issues and improvements. And I think the following article and the links there could help you to answer these questions:
https://docs.microsoft.com/power-bi/fundamentals/service-features-license-type

**Comment by dshimogawa** [comment]
HI, @dariomws .

Thank you reply. Sorry I read this docs before a week.  This situation user connect workplace analytics data on Power BI. This workplace analytics data, this is not my workspace data? I want to know correct information. Are they has power BI Pro necessary if they connect Viva Insights Report?

**Comment by dariomws** [comment]
@dshimogawa, my apologies but I cannot answer that. I think the [Tech Community](https://techcommunity.microsoft.com/) might be a better place to ask this question.

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
