### ISSUE TITLE
Feature Request: Ability to disable reminders for Viva scheduled events

### ISSUE THREAD

**Issue by jmdatasci** [MicrosoftDocs/Viva#347]
Looking to see if there was some way to by default let Viva block my calendar time but prevent sending notifications/reminders before events while still allowing my default calendar to have the advanced 15 minute reminder. 

Current solution is to individually change each event.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
