### ISSUE TITLE
Setup App - URL Clarification

### ISSUE THREAD

**Issue by JASTOKER** [MicrosoftDocs/Viva#349]
In the setup app section of https://docs.microsoft.com/en-us/viva/insights/setup/set-up-workplace-analytics we see the following text **"[Open the app](https://workplaceanalytics.office.com/). (If that link doesn't work, try [this link instead](https://workplaceanalytics-eu.office.com/).)"** 

This is not clear as to when you would need to use the EU URL over the original, it would be good to have additional messaging as to why one of the URLS may not work in some tenants instead of having to try both.

**Comment by dariomws** [comment]
Hi @JASTOKER, thank you for your feedback.

@lilyolason, could you help here? Could we provide more information? I see that you have applied this update to several articles. Thanks!

**Comment by dariomws** [comment]
@lilyolason, could you help here? Could we provide more information? I see that you have applied this update to several articles. Thanks!

**Comment by scanum** [comment]
Thank you for your insight and contribution to the docs. Closing this issue since the team is actively working on a solution that is going to be live in the near future.
