### ISSUE TITLE
Collaboration Weekly Average

### ISSUE THREAD

**Issue by aswayze-ops** [MicrosoftDocs/Viva#351]
This is a gross misrepresentation of calculations. It's not calculating the time it took to actually writing up that email. There's the start time, the time's interrupted the end time and the time it was actually sent? You can't base an average time spent on emails.

![image](https://user-images.githubusercontent.com/65136786/180217460-3cad36cb-2d1d-4031-ba16-9acfdb0f4b8d.png)

![image](https://user-images.githubusercontent.com/65136786/180217403-9ac96f68-5aa7-4de6-9f6e-9c1cdb768515.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
