### ISSUE TITLE
Sharepoint as provider not showing

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [MicrosoftDocs/Viva#352]
We have followed all the steps below but can still not see SharePoint. We are on a free trial and are evaluating it.

![image](https://user-images.githubusercontent.com/30843127/180327653-cc0b929a-9273-453b-9401-6bf5895dd788.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://docs.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
