### ISSUE TITLE
Despite opting out of Viva I get the absurdly annoying emails from Viva, and I cannot block them in outlook

### ISSUE THREAD

**Issue by Sensative-Lars-Mats** [MicrosoftDocs/Viva#353]
[Skriv din feedback här]

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 3fd00309-d5d2-21e8-d68b-eb11526a5fec
* Version Independent ID: 6f37eac2-d7af-5ceb-cd09-31d14efdb8c8
* Content: [Viva Insights Home page](https://docs.microsoft.com/sv-se/viva/insights/personal/Use/home-web)
* Content Source: [Viva/insights/personal/Use/home-web.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/home-web.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
