### ISSUE TITLE
Viva Connections feed improvements on mobile

### ISSUE THREAD

**Issue by sinansuer** [MicrosoftDocs/Viva#357]
The article indicates that "over time we will be moving over to a machine learning model that is optimized for user engagement while preserving the ability for organizations to lift important content that is recent to the top of users Feeds." 
However, the Mobile experience for Viva Connections Feed already displays "Show more like this" / "Show less like this" buttons for feed items.  Customers are asking how this is impacting the overall Feed ranking. 
It would be great to include an explanation on how "Show more like this" works, in this FAQ article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d23114d5-dc01-a971-c612-67204069a677
* Version Independent ID: d23114d5-dc01-a971-c612-67204069a677
* Content: [Frequently asked questions about the Feed for Viva Connections](https://docs.microsoft.com/en-us/viva/connections/faqs-viva-connections-feed)
* Content Source: [Viva/connections/faqs-viva-connections-feed.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/faqs-viva-connections-feed.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by saashby** [comment]
Thanks Sinan for raising this, we've seen new options showing up for customers in the Connections Feed on mobile like this:
![image](https://user-images.githubusercontent.com/47980322/180754397-4e89f04a-84a6-45bd-be41-12d45fd9a2a5.png)

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
