### ISSUE TITLE
Allow user to delay e-mail even when not suggested by Viva Insights

### ISSUE THREAD

**Issue by javiernegro** [MicrosoftDocs/Viva#358]
This is a great feature! Unfortunately, Viva doesn't always know when we want to use it!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by javiernegro** [comment]
I think there is a mistake. This is not an issue to be resolved, it is a feature request!
