### ISSUE TITLE
missing in viva docs tree

### ISSUE THREAD

**Issue by GeorgeUgly** [MicrosoftDocs/Viva#359]
[Enter feedback here]
this article is missing in viva docs tree and can't be searched.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6418d8f-38d8-38f2-9acb-6620d6022378
* Version Independent ID: a6418d8f-38d8-38f2-9acb-6620d6022378
* Content: [Partitions for Viva Insights](https://docs.microsoft.com/en-us/viva/insights/setup/partitions-wpa#feedback)
* Content Source: [Viva/insights/Setup/partitions-wpa.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Setup/partitions-wpa.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Thanks for your feedback!

**Comment by tiburd** [comment]
Passed on info to documentation team. Closing this issue.
Thanks!
