### ISSUE TITLE
Outlook email sent when Viva Delay Delivery added

### ISSUE THREAD

**Issue by MlleBaeten** [MicrosoftDocs/Viva#360]
This is an intermittent error that I have encountered twice:
While I am composing a reply in the Outlook desktop reading pane, Viva Insights shows the message above the sender suggesting I add Delay Delivery.
I click to schedule it, the Viva panel expands, and I click the option to send this email at the suggested date-time.
Then the Reply window closes and I'm looking at the original email again. 
When I go to my Sent folder, I see the partially constructed email, with the tag at the top that it will be sent at the scheduled time. I can't edit the incomplete email anymore, but I can go to 'Resend' and revise the email, and I see again the header that "After you press Send, the email will be scheduled sent on..."
I'm unsure if the recipient is receiving both copies, and if so, if the first copy was sent immediately or if they are both delayed.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by MlleBaeten** [comment]
@scanum thanks for the link, unfortunately I'm not an admin for our Microsoft tenant (I work elsewhere in our IT dept). There doesn't seem to be any channel a non-admin can submit a support request directly to MS, which is one reason I submitted this here. (Another reason is I couldn't find a Feedback page for the feature).
Just sent it as an FYI. If it happened twice for me, I'm probably not the only one who experienced the issue, so hopefully someone in an admin role can push it up the chain.
