### ISSUE TITLE
Spelling mistake in Viva Goals

### ISSUE THREAD

**Issue by georgia-e** [MicrosoftDocs/Viva#378]
In the Viva Goals app on Teams organization is misspelled as "orhanization"

Can be found when assigning someone to a Task within a Project in Viva Goals, the prompt is "search users in your orhanization"

![image](https://user-images.githubusercontent.com/110805365/183346258-794a2f8d-8166-44c3-8459-0621fabdd28b.png)

**Comment by dariomws** [comment]
@georgia-e, thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and how to make Microsoft products better. They keep a close tab on user feedback and it would be awesome if you could add your voice to the Microsoft Feedback Portal: https://feedbackportal.microsoft.com/feedback/.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to making the docs better! Much appreciated!

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
