### ISSUE TITLE
Automatic upload of Organization Data into Viva Advanced insights

### ISSUE THREAD

**Issue by Balamurugan-dot** [MicrosoftDocs/Viva#380]
Is there anyway we can automate this process without using .CSV file upload approach??

Because our customer looking for the possibility to do a direct sync between Viva insights and azure ad and dynamics 365 without exporting and uploading data as excel sheets as their current data in insights is an year old and they want to either automatically update the data or delete previous data and start from scratch again.

Thanks!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
