### ISSUE TITLE
Possibly incorrect information

### ISSUE THREAD

**Issue by rebeccadh-s** [MicrosoftDocs/Viva#384]
Q1 says that data comes from a leader's Outlook and Teams. However, the other documentation states that it comes from organizational data in Advanced Insights, and that the leader must have the "Analyst (Limited)" role assigned. Which is true? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 112b71c1-2c9b-fd39-ce2b-69cbc74461b7
* Version Independent ID: 112b71c1-2c9b-fd39-ce2b-69cbc74461b7
* Content: [FAQ for My organization insights](https://docs.microsoft.com/en-us/viva/insights/use/myorg-faq)
* Content Source: [Viva/insights/Use/myorg-faq.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/myorg-faq.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @rebeccadh-s, thank you for your feedback.

The entire article was removed and I think it was replaced by:
https://docs.microsoft.com/viva/insights/org-team-insights/org-trends-faq

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
