### ISSUE TITLE
Documentation is misleading about "required fields"

### ISSUE THREAD

**Issue by Jasthin** [MicrosoftDocs/Viva#388]
Under "Rules for Field Headers", the documentation reads: 
_"The required TimeZone field values must be in a supported Windows format
The required Layer field values must contain numbers only
The required HourlyRate field values must contain numbers only, which the app assumes is in US dollars for calculations and data analysis"_

This is misleading. Timezone, Layer and Hourly Rate are NOT required fields. Can we please change the language here as its confusing for customers. Simply removing the word "required" should solve the problem. 

Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34abca1c-0119-7997-9365-aee51c2bb506
* Version Independent ID: fdd27a3e-71a3-4886-8b9c-f9e772925cd2
* Content: [First organizational data upload](https://docs.microsoft.com/en-us/viva/insights/setup/upload-organizational-data-1st)
* Content Source: [Viva/insights/Setup/upload-organizational-data-1st.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Setup/upload-organizational-data-1st.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Thanks for your feedback!
