### ISSUE TITLE
Focus Time no longer using Green Category in Outlook

### ISSUE THREAD

**Issue by b1g0af** [MicrosoftDocs/Viva#394]
My Viva Insights-booked Focus Time is no longer getting the Green Category applied to it in Outlook. I found this closed issue from 2020, #107, that calls out "don't change the name of the Green Category," but I have not changed its name. This issue has persisted past several reboots, so it's not a transient issue.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by hisuwh** [comment]
I'm also seeing this @b1g0af did you get anywhere with support?

**Comment by alimayy** [comment]
I have the same issue - m Focus Times became the default blue out of nowhere as far as I can tell. Didn't change the category name, didn't change anything.

**Comment by forbushbl** [comment]
I'm seeing the same issue. My green category seems to still be intact

![Screen Shot 2022-09-15 at 4 48 32 PM](https://user-images.githubusercontent.com/187220/190521950-6e221742-c3a0-4135-a00f-d33104b50a23.png)

**Comment by marcodenic** [comment]
Also getting this issue on a default install of outlook, no changes to categories. Messing with, deleting or readding the green category has no effect.
