### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/Viva#396]
It should be noted that this still doesn't work on iPad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccca9392-e576-ef1f-79f5-f591810db155
* Version Independent ID: ccca9392-e576-ef1f-79f5-f591810db155
* Content: [Overview: Viva Connections](https://docs.microsoft.com/en-us/viva/connections/viva-connections-overview#viva-connections-mobile-and-desktop-experiences)
* Content Source: [Viva/connections/viva-connections-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/viva-connections-overview.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
@danmyhre We do have that note in the notes section at the top of the article. Would it be helpful to reiterate the note somewhere else in the article?

**Comment by danmyhre** [comment]
That doesn't seem to be accurate though. It works on Android tablets, but is still unsupported on iPads.

**Comment by Holland-ODSP** [comment]
That's good to know @danmyhre - can you tell me about the Android model name?

**Comment by danmyhre** [comment]
My test android device is a Samsung Galaxy Tab A (SM-T510)

**Comment by scanum** [comment]
Hi @Holland-ODSP Hope all is well. is there an update here? Thanks.

**Comment by scanum** [comment]
Hi @Holland-ODSP Hope all is well. is there an update here? Thanks.

**Comment by Holland-ODSP** [comment]
The app is now available on tablet devices so we can close this.
