### ISSUE TITLE
Sent time

### ISSUE THREAD

**Issue by AdditionAddict** [MicrosoftDocs/Viva#398]
Unclear from the page if the sent time recipient receives will be the true time sent or show the delayed time.

I don't want the recipient to know if I sent it in the early hours of the morning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90e3dc0-1995-0752-d42f-bf29a1f225b6
* Version Independent ID: d2717304-5311-4778-a6a1-50ba6578725a
* Content: [Delay delivery plan with Viva Insights](https://docs.microsoft.com/en-us/viva/insights/personal/use/delay-delivery)
* Content Source: [Viva/insights/personal/Use/delay-delivery.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Use/delay-delivery.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
Hi @AdditionAddict, thank you for your feedback.

The function is "delayed delivery", the email will be sent in the specified time, and therefore the sending time will be the same for both (sender and recipient).

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
