### ISSUE TITLE
No storyline tab in viva engage

### ISSUE THREAD

**Issue by ZadilHK** [MicrosoftDocs/Viva#399]
Hello, 
Our school organization is connected to the Office 365 account and i installed viva engage via the MS team app  but there is no storyline tab. Please advice.

Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
