### ISSUE TITLE
Is it possible to get the location of the meeting and analyze whether it is an onsite or online meeting?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#404]
[Enter feedback here]
Hi, team.

Some customer want to analyze meetings rocation about an onsite or online meeting. Can Viva Insights query that get teams meetings rocation? I want to know specification it.

Best regards, 
Daishi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4469d66b-61a7-d7c9-6bce-b819a50dc88e
* Version Independent ID: e927f710-e2cb-770c-5322-d29c6ba0e903
* Content: [Meeting queries in Viva Insights](https://docs.microsoft.com/en-us/viva/insights/tutorials/meeting-queries)
* Content Source: [Viva/insights/Tutorials/Meeting-queries.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Tutorials/Meeting-queries.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @dshimogawa, thank you for your feedback.

I understand there is no direct way to differentiate between onsite and online meetings.

But could you elaborate more? For you what is the difference between an online and an onsite meeting? Onsite could be meeting where people connect using a Teams Room device for example?

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
