### ISSUE TITLE
Effective Meetings - Please allow users to customize questions.

### ISSUE THREAD

**Issue by atrainSaaS** [MicrosoftDocs/Viva#405]
Using Viva to automatically send feedback requests to attendees is a great idea, however data on the "effectiveness" of my meeting isn't useful to me. 

I do remote training using Microsoft Teams. I would love to see Viva Insights handle the collection of feedback surveys for me.  That would be a major timesaver.  Microsoft Forms won't do that for me.

Will we get the ability to customize questions in the future?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
