### ISSUE TITLE
No Org Settings available

### ISSUE THREAD

**Issue by Customery** [MicrosoftDocs/Viva#409]
When I log into Exchange Online as a tenant admin, I click on Settings and there is no Org Settings feature.
![image](https://user-images.githubusercontent.com/20672898/190518383-dc67ec04-699a-4f80-aa5f-6c756c9112fb.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26c9627d-a6f3-f38f-82d5-6fe51bc7ea3d
* Version Independent ID: 799ef4ae-7f5b-5fe5-b282-9e8a10c5f259
* Content: [Configure Briefing email](https://docs.microsoft.com/en-us/viva/insights/personal/Briefing/be-admin)
* Content Source: [Viva/insights/personal/Briefing/be-admin.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/Briefing/be-admin.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
