### ISSUE TITLE
Meeting hours definition is not very helpful

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/Viva#410]
I just got a question from Sonja to clarify whether Manager 1:1 and coaching time includes unscheduled Teams calls. It doesn't, and not only does the documentation for that page not state that clearly, but if we look at the definition for "Meeting hours", it offers very little information. "Meeting hours measures time in meetings..." We can probably add a little more information than that! We should also explain that meetings are identified based on Outlook calendars, and appointments that likely represent non-meetings, like all day events or meetings with no other attendees, are generally excluded from the measure.  Then at least someone who sees that Manager 1:1 time measures meeting hours could fall back on the meeting hours definition to get more detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4929397-66a3-43c5-b0dd-8696bd02127a
* Version Independent ID: 04d71a91-f0f9-e87e-1be5-4d1dedc85c77
* Content: [Metric definitions for Advanced insights](https://learn.microsoft.com/en-us/viva/insights/use/metric-definitions)
* Content Source: [Viva/insights/Use/Metric-definitions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/Use/Metric-definitions.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
