### ISSUE TITLE
IPs for Tableau

### ISSUE THREAD

**Issue by rcwoolston** [MicrosoftDocs/Viva#411]
The IPs should just be listed in the doc. We talked to our customer service rep and he was unable to locate who knew which IPs they were.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c7185389-4664-77ad-1291-fd0dfd0e98ff
* Version Independent ID: c7185389-4664-77ad-1291-fd0dfd0e98ff
* Content: [Tableau Integration](https://learn.microsoft.com/en-us/viva/goals/tableau-integration)
* Content Source: [Viva/goals/tableau-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/tableau-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ms-vikashkoushik
* Microsoft Alias: **vsreenivasan**

**Comment by dariomws** [comment]
Hi @rcwoolston, thank you for your feedback.

We cannot list the IP addresses for Tableau Cloud in this article because it's maintained by them. You can find it in the Tableau Help site.

**Comment by scanum** [comment]
The [Microsoft Open Source Code of Conduct][1], which outlines the expectations for community
interactions in and around docs.microsoft.com, is designed to help provide a welcoming and inspiring
community for all. The content of this issue appears to be out of sync with the code of conduct,
so we have closed it.

[1]: https://opensource.microsoft.com/codeofconduct/
