### ISSUE TITLE
Insights Reflection History Broken

### ISSUE THREAD

**Issue by Lesswater** [MicrosoftDocs/Viva#412]
Just started using Viva Insights Reflections (How are you feeling?) - I have not been able to see Reflection History after the 2nd or 3rd time I tried opening it  Please see error page screenshot.

![reflectionHistory](https://user-images.githubusercontent.com/14861868/191773073-3edf1133-81b7-4f00-ae64-dbad869574c8.png)
![reflectionHistoryError](https://user-images.githubusercontent.com/14861868/191773081-3b393206-b308-4d4a-9cce-247c295f7f32.png)

**Comment by rpeimbert** [comment]
This has been an issue for me for roughly 2 weeks.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
