### ISSUE TITLE
how to: add the Viva Insights Outlook add-in yourself from the Microsoft Store Add-ins

### ISSUE THREAD

**Issue by ltwhite** [MicrosoftDocs/Viva#413]
"you can manually add the Viva Insights Outlook add-in yourself from the Microsoft Store Add-ins."

Need to include steps for how to do this!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7ad0de9-1db2-4180-3863-a59c8b0ae030
* Version Independent ID: e87a0970-fa67-3cce-c885-cde6c6246e33
* Content: [About Viva Insights Outlook add-in](https://learn.microsoft.com/en-us/viva/insights/personal/use/add-in)
* Content Source: [Viva/insights/personal/use/add-in.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/use/add-in.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @ltwhite, thank you for your feedback.

Please read the following article to get add-ins for Outlook:
https://support.microsoft.com/office/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
