### ISSUE TITLE
Unclear instruction

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/Viva#414]
Hello,

Articles about deploying Viva Goals need a lot of work. I am missing a clear instruction on how to setup it (setup described in this article says only about the Goals org setup, nothing anywhere about deploying Viva Goals). Couldn't we have something short that would say:
1. Get license
2. Unlock it in Manage apps in teams admin center (yeah i know we have this https://learn.microsoft.com/en-us/viva/goals/configure-ms-teams-integration but see where it is in the structure of viva goals articles)
3. Go here and here to setup org and permissions.

The link to goals.microsoft.com was not written anywhere (or at least i couldn't find it) - only in a template under Adoption Guide.
The article "Navigate the admin Dashboard" explains how to navigate the admin center but it is not written ANYWHERE, where one can find said admin center. It's not listed as an app here:
https://www.office.com/apps?auth=2&home=1

How are people supposed to know the link is goals.microsoft.com???

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d5be45c-c23d-3c60-b0cd-1a12669d8e72
* Version Independent ID: 2d5be45c-c23d-3c60-b0cd-1a12669d8e72
* Content: [Navigate the admin dashboard](https://learn.microsoft.com/en-us/viva/goals/navigate-admin-dashboard?source=recommendations)
* Content Source: [Viva/goals/navigate-admin-dashboard.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/navigate-admin-dashboard.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ranjali-MS
* Microsoft Alias: **ranjaliroy**

**Comment by get-itips** [comment]
Hello @bozenektoja 
Article was updated to add the mentioned link.
About the other feedback: I am looking into that.
Thanks
