### ISSUE TITLE
Helpful Information for VIVA Goals

### ISSUE THREAD

**Issue by tmpowell333** [MicrosoftDocs/Viva#417]
Please add a link (goals.microsoft.com) to the product documentation. As I found it very difficult to find the VIVA Goals login page. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d21e7581-8e7e-a0da-0bae-d391ecf0ab1b
* Version Independent ID: d21e7581-8e7e-a0da-0bae-d391ecf0ab1b
* Content: [Log in, create, and join organizations in Viva Goals](https://learn.microsoft.com/en-us/viva/goals/log-in-create-and-join-organizations)
* Content Source: [Viva/goals/log-in-create-and-join-organizations.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/log-in-create-and-join-organizations.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ms-vikashkoushik
* Microsoft Alias: **vsreenivasan**

**Comment by get-itips** [comment]
Hello,
Information was added to the article.
Thank you for your feedback
