### ISSUE TITLE
Your support pages suck

### ISSUE THREAD

**Issue by MKaiserPhD** [MicrosoftDocs/Viva#418]
Every time I Google some question I have with a Microsoft product and then select Microsoft support, I kick myself.  I just spent 20 minutes trying to solve a simple problem - how to turn off Focus time in my calendar.  I still haven't figured it.   How do I find "viva insights," "my dashboard," "from the protect your time tab,"  "productivity insights," etc.  Select the gear icon gets me nothing.  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1be587-349a-ef1f-7fac-85bdd891335a
* Version Independent ID: 206cc387-8b5c-2e72-b4d5-57e3ac21c217
* Content: [Focus plan for Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/use/focus-plan)
* Content Source: [Viva/insights/personal/use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/use/focus-plan.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
