### ISSUE TITLE
Viva Insights Add-in Error

### ISSUE THREAD

**Issue by jtsoulos** [MicrosoftDocs/Viva#420]
I find Viva Insights and the ability to easily delay delivery in outlook using this add-in incredibly helpful. The problem is, I keep getting an "Add-in Error" that says "sorry, we couldn't load the add-in because Internet Explorer is disabled. Click "see Details" for more information." Our IT dept has fixed this a few times, but each time my computer restarts, it requires someone from IT to enable Internet Explorer again. I am not enabled to do this myself. Now our IT dept says they are not allowed to enable IE since it has been retired. Can Microsoft Viva fix this? It seems odd to link Viva with a tool that has been retired by the company. Does anyone have a suggested fix?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
