### ISSUE TITLE
Could you tell me about "License Requirement" ?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#421]
[Enter feedback here]
Hi, team.
I want to use "Effective meetings in Viva Insights".  Can I use this function without Viva Insights add-on license?  Our environment use Microsoft 365 E3.

Best regards,
Daishi.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf5f1aa9-70e8-fd4f-c1c0-e5d17f9de677
* Version Independent ID: bf5f1aa9-70e8-fd4f-c1c0-e5d17f9de677
* Content: [Effective meetings in Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/teams/effective-meetings)
* Content Source: [Viva/insights/personal/teams/effective-meetings.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/teams/effective-meetings.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
