### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by VigneshMitsume** [MicrosoftDocs/Viva#423]
Currently Sharepoint online is written as Sharepoint in Microsoft 365 in other documents where as in this document it is mentioned as Sharepoint homesite which brings confusion to the user whether it is about sharepoint in Microsoft 365 or Sharepoint OnPremise versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0b02f6a-d358-1bc4-a9ea-f3599a5eeade
* Version Independent ID: a0b02f6a-d358-1bc4-a9ea-f3599a5eeade
* Content: [Plan, build, and launch a home site for your organization](https://learn.microsoft.com/en-us/viva/connections/home-site-plan?source=docs)
* Content Source: [Viva/connections/home-site-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/home-site-plan.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by get-itips** [comment]
Hello @VigneshMitsume how are you?

This specific article is talking about the home site feature of SharePoint, it is not referring SharePoint Online as "SharePoint homesite",  https://learn.microsoft.com/en-us/sharepoint/home-site

Please let me know if i understood correctly your inquiry.

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
