### ISSUE TITLE
Please specify that sharepoint admin rights are only necessary when using sharepoint content.

### ISSUE THREAD

**Issue by GHSandy** [MicrosoftDocs/Viva#424]
It's not clear that the sharepoint admin rights are only necessary if using sharepoint content. Otherwise this is not required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1cdd9d9-15a7-1d3a-9b0c-f9e053713980
* Version Independent ID: b1cdd9d9-15a7-1d3a-9b0c-f9e053713980
* Content: [Set up Microsoft Viva Learning in the Teams admin center](https://learn.microsoft.com/en-us/viva/learning/set-up-viva-learning)
* Content Source: [Viva/learning/set-up-viva-learning.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/set-up-viva-learning.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Thanks for your feedback
