### ISSUE TITLE
Add the Dashboard web part is no longer in preview

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/Viva#426]
Add the Dashboard web part is no longer in preview. Please can up update the image and remove the word "(Preview)" under point 2. 
![image](https://user-images.githubusercontent.com/69439002/196048770-81bbf3ce-2325-4cda-86e1-409b505b7c1b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c14bb03-a029-8201-b9a4-238c56326261
* Version Independent ID: 1c14bb03-a029-8201-b9a4-238c56326261
* Content: [Use the Viva Connections Dashboard web part](https://learn.microsoft.com/en-us/viva/connections/use-dashboard-web-part-on-home-site?source=recommendations)
* Content Source: [Viva/connections/use-dashboard-web-part-on-home-site.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/use-dashboard-web-part-on-home-site.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nikki-c** [comment]
Hi my feedback was not about a tenant problem have you responded to the wrong person?  My feedback was to ask for the documentation to be updated as the Viva dashboard functionality is no longer in preview. It is now in GA.

**Comment by Holland-ODSP** [comment]
Thanks for letting me know @nikki-c . I just submitted a PR to swap out the image and review any mention of "preview" so this will be updated in less than 24 hours.
