### ISSUE TITLE
Could you please confirm there is a service dependency to Yammer for Viva Connection app?

### ISSUE THREAD

**Issue by alan-hu** [MicrosoftDocs/Viva#427]
Dear Viva Connection team,

When my organization tests Viva Connection app in Teams client, we surprised that Viva Connection app caused a 53003 token issuance error in iOS Teams client, this is due to a custom AAD Conditional Access policy blocking a small set of Office365 services from outside of our trusted networks. But at the same time Android users did not experience the error.

Could there be a late-bound service dependency to Yammer service in Viva Connection iOS app? If so, please include this piece of information in the Viva Connection requirements so admins around the world can properly configure their deployments.

Thanks,
Alan
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 478d00dd-8727-3a3f-4e6b-afd36d3c699e
* Version Independent ID: 478d00dd-8727-3a3f-4e6b-afd36d3c699e
* Content: [Guide to setting up Viva Connections](https://learn.microsoft.com/en-us/viva/connections/guide-to-setting-up-viva-connections)
* Content Source: [Viva/connections/guide-to-setting-up-viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/guide-to-setting-up-viva-connections.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
