### ISSUE TITLE
Plug in vs email: Viva insights when they're out of date

### ISSUE THREAD

**Issue by IT-nerd-85** [MicrosoftDocs/Viva#428]
I'd prefer a plug-in that works with my Outlook so that I'm not reading yet another email that's out of date after the day is complete. Viva Insights notifications are useful in the morning, but by the end of that day I've often completed the items in the email and yet it still sits there, cluttering up my inbox. Viva would work better as a pop up/sidebar notification within Outlook so I can keep up to date with my tasks and messages in real-time.

In addition, Outlook Rules don't allow you to create a rule to delete emails which are X days old - so the only way to get rid of these messages is a manual deletion.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
