### ISSUE TITLE
Viva Goals not in GCC

### ISSUE THREAD

**Issue by Matt-Mueller-MSFT** [MicrosoftDocs/Viva#436]
Can it be included in a note or something on the page that Viva Goal is not yet available for GCC, GCCH and DOD Clouds? Listed as NA here, and on all the internal Roadmaps it says TBD.
https://supportability.visualstudio.com/M365%20Release%20Announcements/_wiki/wikis/M365-Product-Updates.wiki/573963/Viva-Goals

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0ef188-7c51-588e-d5b6-94b847a625f9
* Version Independent ID: 0e0ef188-7c51-588e-d5b6-94b847a625f9
* Content: [Introduction to Microsoft Viva Goals](https://learn.microsoft.com/en-us/viva/goals/intro-to-ms-viva-goals?source=docs)
* Content Source: [Viva/goals/intro-to-ms-viva-goals.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/intro-to-ms-viva-goals.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by get-itips** [comment]
Hello @Matt-Mueller-MSFT How are you?
I am afraid I can not access the link you added here, can you include the exact link to the roadmap item you are talking about? I couldn't find the exact item that talks solely about Goals. Thank you!

About where to add that, probable here is the right article https://learn.microsoft.com/en-us/office365/servicedescriptions/microsoft-viva-service-description

**Comment by get-itips** [comment]
Hello @Matt-Mueller-MSFT could you see my comment here? Thanks

**Comment by get-itips** [comment]
@scanum closing, for now, it can be re-opened.
