### ISSUE TITLE
Viva insights - Timestamp which email was written still visible

### ISSUE THREAD

**Issue by 20211048** [MicrosoftDocs/Viva#439]
Regarding to: https://learn.microsoft.com/en-us/viva/insights/personal/use/schedule-send

I observed a minor issue that should be fixed:
![image](https://user-images.githubusercontent.com/115148305/198546077-e01bf519-38ea-45c7-b9e6-faadc429542c.png)

Even with delay delivery, it is still possible to see the timestamp in which the email was written. 
Both timestamps should be the scheduled moment.

**Comment by get-itips** [comment]
Hello @20211048 
Thanks for the feedback, however, here, we are limited to documentation changes and fixes, for your inquiry the best would be to open a support request or feedback portal https://feedbackportal.microsoft.com/feedback/forum/e59fb6ba-1d1c-ec11-b6e7-0022481f8472
