### ISSUE TITLE
Deploying report to Power BI Service error

### ISSUE THREAD

**Issue by BrianPie** [MicrosoftDocs/Viva#440]
I have downloaded the Power BI Templates for Viva Insights configured them Power BI Desktop.   When I publish  them to workspace the  reports work but I can not set up auto refresh. The datasource credentials are required, when I enter my user name and password ( same on Power BI and Viva Insights)  the error occurs. 

![image](https://user-images.githubusercontent.com/37806945/198582901-9e10db1e-bff3-4d1a-acbe-f273140496b1.png)

**Comment by get-itips** [comment]
Hello @BrianPie  Thanks for the feedback, however, here, we are limited to documentation changes and fixes, for your inquiry the best would be to open a support request from your tenant.
