### ISSUE TITLE
Slack integration not available as documented

### ISSUE THREAD

**Issue by trevonmckay** [MicrosoftDocs/Viva#442]
[This page](https://learn.microsoft.com/en-us/viva/goals/slack-collaborate-with-viva-goals) makes mention that we are able to integrate our Viva Goals instance with Slack; however, when I follow these steps, this option isn't available to me.

![image](https://user-images.githubusercontent.com/18320804/199092156-d5966bf7-a84c-41d7-8240-dec4a87bf24d.png)

**Comment by get-itips** [comment]
Hello @trevonmckay how are you?
For this inquiry, the best would be to open a support request from your tenant.

**Comment by get-itips** [comment]
@scanum
