### ISSUE TITLE
The ability to share objectives via email doesn't exist

### ISSUE THREAD

**Issue by trevonmckay** [MicrosoftDocs/Viva#443]
The screenshot provided in the documentation doesn't match what the actual product shows. I've also tried entering an external email address to the textbox but the product doesn't accept it.

![image](https://user-images.githubusercontent.com/18320804/199092899-bb085410-74f7-4efd-aebf-b408acc2522a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08fb00b8-23b0-27fa-5bef-60d7968881d4
* Version Independent ID: 08fb00b8-23b0-27fa-5bef-60d7968881d4
* Content: [Share objectives](https://learn.microsoft.com/en-us/viva/goals/share-objectives)
* Content Source: [Viva/goals/share-objectives.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/share-objectives.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ranjali-MS
* Microsoft Alias: **ranjaliroy**

**Comment by get-itips** [comment]
Hello, thanks for your feedback!
