### ISSUE TITLE
Acceptance error

### ISSUE THREAD

**Issue by Variedz97** [MicrosoftDocs/Viva#447]
I try and this is the result

```
PS C:\Windows\system32> Set-SPOHomeSite-HomeSiteUrl "https://redsolvers.sharepoint.com/sites/Intranet" -VivaConnectionsDefaultStart $false

Set-SPOHomeSite-HomeSiteUrl : El término 'Set-SPOHomeSite-HomeSiteUrl' no se reconoce como nombre de un cmdlet,
función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta
de acceso, compruebe que dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ Set-SPOHomeSite-HomeSiteUrl "https://redsolvers.sharepoint.com/sites/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-SPOHomeSite-HomeSiteUrl:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32>

```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ed7c1a9-cdee-5f64-1bf7-119a43e7205f
* Version Independent ID: 0ed7c1a9-cdee-5f64-1bf7-119a43e7205f
* Content: [Customize and edit the Viva Connections home experience](https://learn.microsoft.com/en-us/viva/connections/edit-viva-home)
* Content Source: [Viva/connections/edit-viva-home.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/edit-viva-home.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
@Variedz97 Hi Fabian! 

The reason you got the error is you needed a space between "Set-SPOHomeSite" and "-HomeSiteUrl'"

I am updating the doc so that it's clearer. Going to close this ticket but tag me again if you have trouble.

**Comment by Variedz97** [comment]
Thank you very much indeed @Holland-ODSP 

```
PS C:\WINDOWS\system32> Connect-SPOService -Url https://redsolvers-admin.sharepoint.com
PS C:\WINDOWS\system32> Set-SPOHomeSite -HomeSiteUrl "https://redsolvers.sharepoint.com/sites/Intranet" -VivaConnectionsDefaultStart $false

Confirmar
Before you set a Home site, make sure you review the documentation at https://aka.ms/homesites. Continue?
[S] Sí  [N] No  [U] Suspender  [?] Ayuda (el valor predeterminado es "S"): s

Value
-----
The Home site has been set to https://redsolvers.sharepoint.com/sites/Intranet and the Viva Connections default expe...


PS C:\WINDOWS\system32>
```
