### ISSUE TITLE
Missing illustration or link to illustration

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/Viva#449]
In the section Roles and responsibilities, there is no illustration  or link to the illustration mentioned in the following sentence

> The following illustration shows the central position of the data controller (your organization) between the data subject (left) and the data processor, Microsoft (on the right):

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26e11463-62d3-e600-e8a6-d53b692fdfa9
* Version Independent ID: 26e11463-62d3-e600-e8a6-d53b692fdfa9
* Content: [Advanced insights privacy](https://learn.microsoft.com/en-us/viva/insights/advanced/privacy/privacy#data-protection-considerations)
* Content Source: [Viva/insights/advanced/privacy/privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/privacy/privacy.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
Hi @nikki-c, Thank you for submitting feedback. The article was updated to include the screenshot. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
