### ISSUE TITLE
open rate expiration period

### ISSUE THREAD

**Issue by erinosborn** [MicrosoftDocs/Viva#451]
I sent an email using the delayed delivery feature. When I went to check the open rate, I got the error message not being able to view open rates because of the 14-day expiration period. The email went out a week ago, so I assume the 14 days are being measured from when I scheduled the email. This doesn't make much sense - I feel like it should always be 14 days from the send date. Under the existing logic, if I were to schedule an email more than 2 weeks in advance, I would not be able to get ANY data on open rates.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
