### ISSUE TITLE
Broken link for Viva Insights

### ISSUE THREAD

**Issue by robfinney** [MicrosoftDocs/Viva#457]
Looking for information around Viva Insights specifically from a set up perspective. I located this page: https://learn.microsoft.com/en-us/viva/setup-microsoft-viva and then tried the "Learn how to set it up" link within Viva Insights:  https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/setup-overview.md

This returned a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ea36b7-60d6-14f0-1de6-69ca14043538
* Version Independent ID: 72ea36b7-60d6-14f0-1de6-69ca14043538
* Content: [Set up Microsoft Viva](https://learn.microsoft.com/en-us/viva/setup-microsoft-viva)
* Content Source: [Viva/setup-microsoft-viva.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/setup-microsoft-viva.md)
* Service: **viva**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by LoreenLa** [comment]
Thank you! This is fixed.

From: Rob Finney ***@***.***>
Sent: Tuesday, November 15, 2022 12:35 AM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Loreen La Penna ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Viva] Broken link for Viva Insights (Issue #457)


Looking for information around Viva Insights specifically from a set up perspective. I located this page: https://learn.microsoft.com/en-us/viva/setup-microsoft-viva<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fviva%2Fsetup-microsoft-viva&data=05%7C01%7Cloreenl%40microsoft.com%7C4e80117e6f3b4d78d6dd08dac6e455f4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638040981257374125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EBKbBkDyQXCDPwnU7xcE2jls5SvfdnTI31L9g4v9phg%3D&reserved=0> and then tried the "Learn how to set it up" link within Viva Insights: https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/setup-overview.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fviva%2Finsights%2Fadvanced%2Fsetup-maint%2Fsetup-overview.md&data=05%7C01%7Cloreenl%40microsoft.com%7C4e80117e6f3b4d78d6dd08dac6e455f4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638040981257374125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vP19veNfRJW50lMrQYsyqWWEN%2BRReBSpVOmXFs7yPTE%3D&reserved=0>

This returned a 404.

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 72ea36b7-60d6-14f0-1de6-69ca14043538
  *   Version Independent ID: 72ea36b7-60d6-14f0-1de6-69ca14043538
  *   Content: Set up Microsoft Viva<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fviva%2Fsetup-microsoft-viva&data=05%7C01%7Cloreenl%40microsoft.com%7C4e80117e6f3b4d78d6dd08dac6e455f4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638040981257374125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EBKbBkDyQXCDPwnU7xcE2jls5SvfdnTI31L9g4v9phg%3D&reserved=0>
  *   Content Source: Viva/setup-microsoft-viva.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-WorkplaceAnalytics%2Fblob%2Fpublic%2FViva%2Fsetup-microsoft-viva.md&data=05%7C01%7Cloreenl%40microsoft.com%7C4e80117e6f3b4d78d6dd08dac6e455f4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638040981257374125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K0xUdS9Sc1lv6pG3CB4xmaNLq2iumdWt%2BOYqzDDsBTI%3D&reserved=0>
  *   Service: viva
  *   GitHub Login: @LoreenLa<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLoreenLa&data=05%7C01%7Cloreenl%40microsoft.com%7C4e80117e6f3b4d78d6dd08dac6e455f4%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638040981257374125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JJGhj%2Fgw7kGIf9RytbuyYlnwadXt59BAfPb4ic7kD98%3D&reserved=0>
  *   Microsoft Alias: loreenl
