### ISSUE TITLE
Outlook add-on without Internet Explorer

### ISSUE THREAD

**Issue by alekon2023** [MicrosoftDocs/Viva#460]
Hello, 
Internet Explorer was decommissioned by Microsoft, and we are removing it from all devices. Viva Outlook add-in still require it and documentation is not updated either. 
Are there any plans to move it further without IE? 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/118742457/203067129-d138b917-3b29-4f8c-9a23-bd2583626844.png">

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
