### ISSUE TITLE
No integration for Dynamics

### ISSUE THREAD

**Issue by standswell** [MicrosoftDocs/Viva#461]
This link suggests there is an integration for MS Dynamics, but the Integrations page does not show it as available.

https://learn.microsoft.com/en-us/viva/goals/vg-integrations-administration-overview

![Capture](https://user-images.githubusercontent.com/74499298/203114180-b140c605-51cd-42ad-85d0-3290090994bc.PNG)

**Comment by get-itips** [comment]
Hello, @standswell 
I am looking into this.

**Comment by get-itips** [comment]
Hello @standswell 
I was informed that the integrations are now enabled at tenant level.
Hope this information helps you,

**Comment by get-itips** [comment]
You can follow these instructions if you are the Global Admin of the tenant, to find tenant-level integrations

https://learn.microsoft.com/en-us/viva/goals/vg-integrations-administration-overview#how-to-manage-integrations

**Comment by standswell** [comment]
@get-itips  Great work...thank you!
