### ISSUE TITLE
PQMT: [Viva Insights] Item titles in the app do not correspond to the ones listed in the docs (employee-wellbeing)

### ISSUE THREAD

**Issue by Saki-Yufu** [MicrosoftDocs/Viva#463]
**[URL]**　 
https://learn.microsoft.com/en-us/viva/insights/org-team-insights/employee-wellbeing
 
**[Description]**　 
Item titles in the app do not correspond at all to the ones listed in the docs.
Users say that they have difficulty understanding Viva Insights app.
Because the heading names of docs and the item titles of the app do not correspond at all.
They want to use the app with reading the docs, but they are getting confused more for the above reasons.
It is recommended that the heading names of the documents be the same as the report titles of Viva Insights app.
In this case, we propose to match the titles of the app, but it can be in either docs or app format.

**[Actual]**　 
Inconsistent report titles between the docs and the app.
![20221118_3a](https://user-images.githubusercontent.com/103729056/203245702-6acdaee2-797e-4dbf-96b7-fae796131054.png)

**Docs**
1) Help employees disconnect
2) Focus without interruptions
3) Reduce meeting hours
4) Improve team cohesion

**App**
1) Balance: Protect time outside of working hours
2) Capacity: Help teams find time to finish their work
3) Capacity: Keep a pulse on collaboration overload
4) Community: Drive team cohesion and alignment through shared activities and projects

**[Expected]**　 
Use the same title for the docs and the apps.
1) Balance: Protect time outside of working hours
2) Capacity: Help teams find time to finish their work
3) Capacity: Keep a pulse on collaboration overload
4) Community: Drive team cohesion and alignment through shared activities and projects

[Source] 
Japan Internal Feedback 

[Copied from] 
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/E7Cd4odt56NOgiYrOP5xzpcBtOvfh92aF7jwMXHI3qWQ7g?e=xXUIR8

**Comment by dariomws** [comment]
@Saki-Yufu, Thank you for submitting feedback. The article was updated. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Saki-Yufu** [comment]
@dariomws,
I checked Viva Insights and the documents by comparing them. Thank you for the fix!

**Comment by dariomws** [comment]
@Saki-Yufu, thank you for submitting feedback and help us to improve documentation!
