### ISSUE TITLE
PQMT: [Viva Insights] Item titles in the app do not correspond to the ones listed in the docs (meeting-effectiveness)

### ISSUE THREAD

**Issue by Saki-Yufu** [MicrosoftDocs/Viva#464]
**[URL]**　 
https://learn.microsoft.com/en-us/viva/insights/org-team-insights/meeting-effectiveness
 
**[Description]**　 
Item titles in the app do not correspond at all to the ones listed in the docs.
Users say that they have difficulty understanding Viva Insights app.
Because the heading names of docs and the item titles of the app do not correspond at all.
They want to use the app with reading the docs, but they are getting confused more for the above reasons.
It is recommended that the heading names of the documents be the same as the report titles of Viva Insights app.
In this case, we propose to match the titles of the app, but it can be in either docs or app format.

**[Actual]**　 
Inconsistent report titles between the docs and the app.

**Docs**
1) Try shorter meetings
2) Improve meeting practices
3) Reinvent the recurring meeting

**App**
1) Before the meeting: Structure the meeting for active participation
2) During the meeting: Avoid habits that normalize distractions
3) After the meeting: Examine recurring meetings for oppotunities to win back time

![20221118_3b](https://user-images.githubusercontent.com/103729056/203246700-f26b7ace-0341-4e16-96db-ad9b440c4be4.png)

**[Expected]**　 
Use the same title for the docs and the apps.
1) Before the meeting: Structure the meeting for active participation
2) During the meeting: Avoid habits that normalize distractions
3) After the meeting: Examine recurring meetings for oppotunities to win back time

**[Source]** 
Japan Internal Feedback 

**[Copied from]** 
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/E7Cd4odt56NOgiYrOP5xzpcBtOvfh92aF7jwMXHI3qWQ7g?e=xXUIR8
 
**[Image]** 
20221118_3b.png

**Comment by dariomws** [comment]
@scanum, same as https://github.com/MicrosoftDocs/Viva/issues/463.
