### ISSUE TITLE
PQMT: [Viva Insights] Item titles in the app do not correspond to the ones listed in the docs (manager-connection)

### ISSUE THREAD

**Issue by Saki-Yufu** [MicrosoftDocs/Viva#465]
**[URL]**　 
https://learn.microsoft.com/en-us/viva/insights/org-team-insights/manager-connection 
 
**[Description]**　 
Item titles in the app do not correspond at all to the ones listed in the docs.
Users say that they have difficulty understanding Viva Insights app.
Because the heading names of docs and the item titles of the app do not correspond at all.
They want to use the app with reading the docs, but they are getting confused more for the above reasons.
It is recommended that the heading names of the documents be the same as the report titles of Viva Insights app.
In this case, we propose to match the titles of the app, but it can be in either docs or app format.

**[Actual]**　 
Inconsistent report titles between the docs and the app.

**Docs**
1) Increase frequency of coaching
2) Cultivate autonomy
3) Utilize influencers
4) Foster connectivity

**App**
1) Coaching: Engage with directs through regular 1 on 1 meetings
2) Empowerment: Promote autonomy through guidance and support
3) Empowerment: Empower teams by emphasizing the role of managers as connectors
4) Empowerment: Incorporate fresh ideas and perspectives through broad manager networks

![20221118_3c](https://user-images.githubusercontent.com/103729056/203247483-f3840920-6604-4214-9dd4-bbe25d173f99.png)

**[Expected]**　 
Use the same title for the docs and the apps.
1) Coaching: Engage with directs through regular 1 on 1 meetings
2) Empowerment: Promote autonomy through guidance and support
3) Empowerment: Empower teams by emphasizing the role of managers as connectors
4) Empowerment: Incorporate fresh ideas and perspectives through broad manager networks

**[Source]** 
Japan Internal Feedback 

**[Copied from]** 
https://microsoft.sharepoint.com/:li:/t/ntojapan/pqmt/E7Cd4odt56NOgiYrOP5xzpcBtOvfh92aF7jwMXHI3qWQ7g?e=xXUIR8

**Comment by dariomws** [comment]
@scanum, same as https://github.com/MicrosoftDocs/Viva/issues/463.
