### ISSUE TITLE
Restrict permissions without Teams or Viva Goals license

### ISSUE THREAD

**Issue by joergrenn** [MicrosoftDocs/Viva#469]
Hello,
the admin accounts in our tenant do not have Teams or Viva Goals licenses.
We would like to Restrict organization creation permissions to only global admins.
However in your documentation this is only possible via the Viva Goals App in Teams.
How can a global admin without a Teams or viva Goals license configure these permissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a893c75e-bd6c-a5f0-b97a-857f5e39bec0
* Version Independent ID: a893c75e-bd6c-a5f0-b97a-857f5e39bec0
* Content: [Restrict organization creation permissions](https://learn.microsoft.com/en-us/viva/goals/restrict-organization-creation-permissions)
* Content Source: [Viva/goals/restrict-organization-creation-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/restrict-organization-creation-permissions.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @ranjali-MS
* Microsoft Alias: **ranjaliroy**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
