### ISSUE TITLE
Ability to bulk see OKR Status for each Individual in Admin Panel

### ISSUE THREAD

**Issue by ScalerHuang** [MicrosoftDocs/Viva#470]
Current state:
There's no way to bulk see if a user has added OKRs for the period. The only way is to individually click through every user, but that's not scalable. There's a way to see the status of a user, but it's not the same as seeing if they've added their OKRs for the quarter.

Future state:
Add a function in the admin panel to see if a user has added their OKRs for the time period. It doesn't need to show what their OKRs are, but I want to be able to see if they've put it in the platform or not.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
