### ISSUE TITLE
Automatically Add New Users from O365

### ISSUE THREAD

**Issue by ScalerHuang** [MicrosoftDocs/Viva#471]
Is there a way for the system to automatically send an invitation to a user who has been added to the O365 suite? The new user would have a new email in O365.

I'd like to move away from manually adding new hires.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
