### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by Ovyone** [MicrosoftDocs/Viva#474]
Is it possible to have your organization's home site in a different tenant accessible via Azure AD B2B?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Ovyone** [comment]
Could you clarify whether or not it is even possible?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by scanum** [comment]
Hi @Ovyone hope all is well. Is there a particular article you are referring to? Thanks.
