### ISSUE TITLE
Suggested Feature: Allow adding a category (Color coding) to focus time in Viva Insights

### ISSUE THREAD

**Issue by rmillman** [MicrosoftDocs/Viva#476]
Not sure if this is the place to add this, if not please advise.

Viva Insights allows for creating protected time.  For each of those, it would be helpful if we could apply a category (i.e. color) to the different entries.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
