### ISSUE TITLE
Outdated instructions

### ISSUE THREAD

**Issue by gleversluis** [MicrosoftDocs/Viva#478]
The document is based on the Classic Exchange Admin Center. It requires updating to link to the proper Add-Ins page in the new Exchange Admin Center, which - in contrary to what the page says - is not on the dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91cd3751-42b9-fce0-41ce-25a06cf3d469
* Version Independent ID: fc66fe93-09c7-382a-a7dc-abc5f1043317
* Content: [Disabling the Viva Insights Outlook add-in](https://learn.microsoft.com/en-us/viva/insights/personal/setup/mya-disable-insights)
* Content Source: [Viva/insights/personal/setup/mya-disable-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/setup/mya-disable-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by dariomws** [comment]
Hi @gleversluis, thank you for your feedback.

There is work in progress to update this article. The new location for add-ins should appear soon.
