### ISSUE TITLE
Comparative Data

### ISSUE THREAD

**Issue by wwestlake** [MicrosoftDocs/Viva#480]
While the insights in this system are great, it would make them much more helpful if they contained some normative values to judge them by.  As an example of this, Grammarly tells you that you "Used more unique words in the last month than 78% of their users."  

So, when talking about the number of meetings attended or other factors, it would be helpful to know the norm for these across the organization or as a percentile, such as Grammarly supplies.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
