### ISSUE TITLE
Viva Insights page - Headspace meditations not loading

### ISSUE THREAD

**Issue by yyahav** [MicrosoftDocs/Viva#482]
When trying to load a Headspace meditation on Viva Insights page, I get the following error:
`Sorry, something went wrong. Click to refresh.`

Tried refreshing the page, refreshing by clicking the icon, tried a few meditations, nothing resolves it.

![image](https://user-images.githubusercontent.com/88027106/205849789-dbdf1eed-f9dd-4661-99b3-b7e7b960d3e3.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
