### ISSUE TITLE
Missing illustration

### ISSUE THREAD

**Issue by juchacz** [MicrosoftDocs/Viva#483]
Where it says:

> The following illustration shows the central position of the data controller (your organization) between the data subject (left) and the data processor, Microsoft (on the right):

There is no illustration
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26e11463-62d3-e600-e8a6-d53b692fdfa9
* Version Independent ID: 26e11463-62d3-e600-e8a6-d53b692fdfa9
* Content: [Advanced insights privacy](https://learn.microsoft.com/en-us/viva/insights/advanced/privacy/privacy)
* Content Source: [Viva/insights/advanced/privacy/privacy.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/privacy/privacy.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by lilyolason** [comment]
@scanum and @juchacz -- image added. Thanks!
