### ISSUE TITLE
Sharepoint Site has to be Communication Site (not teams)

### ISSUE THREAD

**Issue by msghaleb** [MicrosoftDocs/Viva#486]
This works only with SharePoint Communication Site - may be its worthy mentioning in the Article :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
@bhaswatic Can you help us confirm here? Thanks

**Comment by bhaswatic** [comment]
Hi @ all - we can confirm this issue and the Viva Content team will make these changes scheduled by the end of the week. PubOps will be helping us merge this. 
Please let me know if you have any questions on the process workflow.

**Comment by get-itips** [comment]
Article was updated.

**Comment by joshtransient** [comment]
This is a really, really, really stupid requirement. I just showed a customer that they can set up M365 Learning Pathways on any site they wanted, so they decided to go with a Yammer-powered M365 Group site so they can have discussions, self-directed M365 training, and corporate Viva Learning training assets in a single location. Now I have to tell them that some **arbitrary requirement** (on top of all the other incredibly tedious prerequisites and lame sharing requirements) prevents them from having a single solution. Great job, Viva Learning team -- you have proven wholeheartedly how little you care about customers who aren't paying for the premium SKU.
