### ISSUE TITLE
Broken link to plan and environment for personal insights

### ISSUE THREAD

**Issue by heikobischoff** [MicrosoftDocs/Viva#488]
In this section:
https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/environment-requirements?source=docs#personal-insights

There is a broken link to https://learn.microsoft.com/en-us/viva/insights/personal/Overview/plans-environments.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 188b8572-e99f-5cb3-800f-3a97e84bfd58
* Version Independent ID: 188b8572-e99f-5cb3-800f-3a97e84bfd58
* Content: [Environment requirements for Viva Insights](https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/environment-requirements?source=docs)
* Content Source: [Viva/insights/advanced/setup-maint/environment-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/setup-maint/environment-requirements.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by lilyolason** [comment]
Hey @heikobischoff -- thanks for submitting this issue. The link should now resolve correctly.
