### ISSUE TITLE
What exactly does "open" mean. What about Reading Pane reading of an email?

### ISSUE THREAD

**Issue by GitRomney** [MicrosoftDocs/Viva#489]
Can the product team clarify what they mean by "open" an email? If a user sees the email in the Reading Pane in Outlook, keeps the email in the reading pane for 10 seconds while they read it, then deletes the email, is the email considered open, or unopened?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3b1941b-9521-b3cc-d10f-1fbc640a0810
* Version Independent ID: a3b1941b-9521-b3cc-d10f-1fbc640a0810
* Content: [Use Microsoft Viva Insights in Outlook](https://learn.microsoft.com/en-us/viva/insights/personal/use/use-insights#track-email-and-document-open-rates)
* Content Source: [Viva/insights/personal/use/use-insights.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/use/use-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Hello @GitRomney 
I am looking into this.

**Comment by get-itips** [comment]
Hello,
I could gather this information for you:

" Confirmed with the engineering team - open means user clicked on the email to read it; we rely on outlook signals to see if the user has read the email.
Q: If a user sees the email in the Reading Pane in Outlook, keeps the email in the reading pane for 10 seconds while they read it, then deletes the email, is the email considered open
A: For this scenario, it will be counted as "Open". "
