### ISSUE TITLE
Viva Insights Top Collaborators missing 

### ISSUE THREAD

**Issue by MaryUSMC** [MicrosoftDocs/Viva#494]
Did the Top collaborators network rings diagram get retired? I used that weekly. It was so helpful to see who was draining my time and who needed more of it. 

![image](https://user-images.githubusercontent.com/58956396/211329521-a493083f-d097-4ba4-85f3-f6158567080d.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
