### ISSUE TITLE
Please add more details on de-identification of report data

### ISSUE THREAD

**Issue by DmitryVorobyov** [MicrosoftDocs/Viva#495]
_> Results show a de-identified list of each measured employee’s productivity metrics_ 

Please add more details on how exactly is the query results data de-identified to alleviate customer concerns. 

For example, report may contain columns like _PersonId_ and _EmployeeID_ - can these be used to identify a person by matching them with data in Azure AD? Or do these get changed by differential privacy?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96ae43ab-8e6d-88c5-3a42-3c82b6f7724b
* Version Independent ID: 96ae43ab-8e6d-88c5-3a42-3c82b6f7724b
* Content: [Person query overview](https://learn.microsoft.com/en-us/viva/insights/advanced/analyst/person-query-overview)
* Content Source: [Viva/insights/advanced/analyst/person-query-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/analyst/person-query-overview.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
Hi @DmitryVorobyov, thank you for your feedback.

I think you can find more information about the reports and metrics here:
https://learn.microsoft.com/viva/insights/advanced/analyst/person-query

And for each metric, you have a description in the Viva Insights portal. Hope it helps.
