### ISSUE TITLE
Viva commuting 

### ISSUE THREAD

**Issue by jempah73** [MicrosoftDocs/Viva#496]
This check out exercise has never worked for me.
![0F956143-538B-44C7-9B16-0489596981DF](https://user-images.githubusercontent.com/122481819/211895814-b2826b3f-5bf8-465d-b6f1-12a2f2f21151.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
