### ISSUE TITLE
Viva Goals "Unable to reach app" within the chat context in Teams

### ISSUE THREAD

**Issue by UncleBoost** [MicrosoftDocs/Viva#497]
![Screenshot 2023-01-13 132056](https://user-images.githubusercontent.com/120522577/212222767-5190aa78-8522-424a-9b38-d8e6c25d95ae.png)
Viva Goals is configured and working in a browser and the app within Teams, though the chat context functionality throws an error - "Unable to reach app"

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
