### ISSUE TITLE
Dynamics 365 Integrations Page for Viva Goals not available in my tenant

### ISSUE THREAD

**Issue by pax85** [MicrosoftDocs/Viva#498]
Hi, 

I can't confirm, that this page is accurate. 
The second part of this screenshot https://learn.microsoft.com/en-us/viva/goals/dynamics-365-integration#tenant-admin-configuration is not available for me:

![image](https://user-images.githubusercontent.com/7982498/212288912-2f225f16-6932-4b5f-a54a-2ff4f36f44f2.png)

There is also no Dynamics 365 integration available from the Admin Page of my organization:
![image](https://user-images.githubusercontent.com/7982498/212289060-d0916267-1cf2-4930-9263-0ccd071a0dcc.png)

Is this page accurate or maybe this is a preview feature not available yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 819e4abd-c544-8d82-3600-0f7835523681
* Version Independent ID: 819e4abd-c544-8d82-3600-0f7835523681
* Content: [Dynamics 365 Integration](https://learn.microsoft.com/en-us/viva/goals/dynamics-365-integration)
* Content Source: [Viva/goals/dynamics-365-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/dynamics-365-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by get-itips** [comment]
Hello @pax85 
I was able to follow the instructions and I do have integrations available by clicking on the settings menu.
Maybe the best, in this case, will be to open a support request from your tenant.
Thank you

**Comment by get-itips** [comment]
@scanum
