### ISSUE TITLE
Slack disappeared

### ISSUE THREAD

**Issue by arlogilbert** [MicrosoftDocs/Viva#500]
Lots of documentation about the Slack integration but Slack has entirely disappeared from within the Slack app so it can not be connected. I get that you want people to use Teams, but we won't use teams so if you'd like us to pay for Viva Goals then we need the advertised Slack integration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dbba70a-b94d-2d80-cd8d-e5b0c6e9ff85
* Version Independent ID: 7dbba70a-b94d-2d80-cd8d-e5b0c6e9ff85
* Content: [Collaborate with Viva Goals in Slack](https://learn.microsoft.com/en-us/viva/goals/slack-collaborate-with-viva-goals)
* Content Source: [Viva/goals/slack-collaborate-with-viva-goals.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/slack-collaborate-with-viva-goals.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @rasanders
* Microsoft Alias: **rasanders**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
