### ISSUE TITLE
Please un-pause Viva Insights Daily Briefing Emails!

### ISSUE THREAD

**Issue by mbiedenstein** [MicrosoftDocs/Viva#504]
I love that you're improving the product, but please continue to allow the Daily Briefing emails in the meantime!  I really relied upon those as part of my productivity and workflow.

![image](https://user-images.githubusercontent.com/123182932/213727604-70c4c6a6-06eb-4ad5-bcbd-3158006ac2ad.png)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
