### ISSUE TITLE
Fully disable Viva Insight Analyses and prohibit the ability for a user to opt-in again

### ISSUE THREAD

**Issue by rviersel** [MicrosoftDocs/Viva#506]
How can we **FULLY** disable Viva Insight Analyses and prohibit the ability for a user to opt-in again.

The checkboxes are all unchecked at [M365 Admin > Home > Setup > Microsoft Viva > Viva Insights], but this doesn't prevent the user to opt-in again. Which is also described _"Users can change them at any time from their dashboard settings page. It may take up to 24 hours for all changes to take effect."_

We also disabled the E3 and E5 license feature "Insights by MyAnalytics" which is switch to OFF.

After this we run a powershell script to opt-out each and every user with a Exchange Online mailbox.
Days after we noticed for existing users they opt-in again.
When asking the user how they did this, they said via https://insights.viva.office.com/

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
