### ISSUE TITLE
how to view your active collaborators in viva insights

### ISSUE THREAD

**Issue by lamckenney** [MicrosoftDocs/Viva#507]
Once a month, I receive a Viva Insights digest email that contains the following:
______________________________________
**Take a deeper look**

**_Focus_**

78% Time available to focus in a typical week

**_Network_**

43 Active collaborators you emailed, met, or chatted with at least a few times

___________________________________

There's a "Learn More" link, so I select it, hoping to access a **complete list of collaborators**. I want to see my full network of collaborators (can't even see a complete list of just the active collaborators either), but there doesn't appear to be any way to do this. I can't find any documentation on how to do it. Why can't I see the full list of everyone that I have collaborated with? That is extremely helpful and useful information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b19572ec-df88-2f34-948f-e4ae020ba1cb
* Version Independent ID: 4e731a37-94c4-dcb6-4e33-5556d45ade77
* Content: [Stay connected with Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/teams/viva-insights-stay-connected)
* Content Source: [Viva/insights/personal/teams/viva-insights-stay-connected.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/teams/viva-insights-stay-connected.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
