### ISSUE TITLE
Change focus color not possible on OSx

### ISSUE THREAD

**Issue by tijmenvangurp** [MicrosoftDocs/Viva#513]
Please add documentation on how to change the focus color for OsX(mac) users. 
https://learn.microsoft.com/en-us/viva/insights/personal/use/focus-plan#calendar-color-settings

Only shows how to do this for windows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1be587-349a-ef1f-7fac-85bdd891335a
* Version Independent ID: 206cc387-8b5c-2e72-b4d5-57e3ac21c217
* Content: [Focus plan for Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/use/focus-plan)
* Content Source: [Viva/insights/personal/use/focus-plan.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/use/focus-plan.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
Hi @tijmenvangurp, thank you for your feedback.

Conditional formatting is not available in Outlook for Mac. You may want to vote for it here:
https://feedbackportal.microsoft.com/feedback/idea/46d66991-b995-ec11-a81c-000d3a0f04fc

**Comment by tijmenvangurp** [comment]
Done!

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
