### ISSUE TITLE
Rollup Contributions

### ISSUE THREAD

**Issue by edmc774** [MicrosoftDocs/Viva#518]
Before Microsoft purchased Ally.io, the progress of OKRs that were set to a metric value, and had child OKRs rolling up into it, allowed administrators and OKR owners to change the weights of the contributors.  Now, the default behavior is to only allow a straight-line average between the child OKRs.  This is a problem in many different scenarios.  The most obvious example is a set of different product sales targets rolling into a total.  Suppose you had 3 products using the following targets: P1 = $100,000, P2 = $20,000, and P3 = $1,000.  The default behavior is to treat each one as 33.3% of the goal rather than 82.6%, 16.5%, and 0.8% of the goal. 

Is that feature still available?  If not, will it be corrected?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
