### ISSUE TITLE
Include conditional access capabilities as part of the best practices for rollout

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#519]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Recently, conditional access capabilities are now available for Viva Goals as part of this announcement: 

https://techcommunity.microsoft.com/t5/microsoft-viva-blog/make-your-goals-a-reality-with-okrs-and-new-capabilities-from/ba-p/3711899

For example: 

> By using new updates with Azure Active Directory (AAD), Viva Goals admins can now set up [Conditional Access](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/overview) policies, making sure that the right users have access to the right data. Our identity updates also include AAD identity federation using 3rd party identity solutions: [OKTA](https://adoption.microsoft.com/files/viva/goals/How-to-federate-OKTA-with-AAD.pdf) and [Google](https://adoption.microsoft.com/files/viva/goals/How-to-federate-Google-with-AAD.pdf).

 

Additionally, we are excited to announce the availability of EU Data Residency for new Viva Goals customers. EU Data Residency will be available for Ally.io customers migrating to Viva Goals by the end of January 2023. This update means that EU-based or multi-national customers can store their data in EU data centers.

Please include this capability in the guidance as part of best practices when rolling out the product. Including a link back to conditional access for more information: https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/overview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e0ef188-7c51-588e-d5b6-94b847a625f9
* Version Independent ID: 0e0ef188-7c51-588e-d5b6-94b847a625f9
* Content: [Introduction to Microsoft Viva Goals](https://review.learn.microsoft.com/en-us/viva/goals/intro-to-ms-viva-goals)
* Content Source: [Viva/goals/intro-to-ms-viva-goals.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/intro-to-ms-viva-goals.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by dariomws** [comment]
Hi @soyalejolopez, if you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html 

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=@soyalejolopez

**Comment by dariomws** [comment]
@soyalejolopez, thank you for your feedback.

Could you kindly provide more detail? Where to add CA information? https://learn.microsoft.com/viva/goals/determine-your-rollout-plan? How?

I don't think that we have too much information on each Microsoft product or service account conditional access policies. For example, for Exchange Online I cannot find an article. For SP and OD, I only found this:
https://learn.microsoft.com/sharepoint/enable-conditional-access
Teams:
https://learn.microsoft.com/microsoftteams/rooms/conditional-access-and-compliance-for-devices

I'm not sure how to add information about CAP to Viva Goals as there are not guidelines to follow from the other products.

**Comment by soyalejolopez** [comment]
Hi @dariomws, thanks for following up. It looks like we don't have documentation for enabling Conditional Access for Viva Goals despite it having some pre-reqs in order to enable. A potential option how to include that guidance could be the following: 

- Include row item under "[Setup and Administration](https://learn.microsoft.com/en-us/viva/goals/intro-to-ms-viva-goals#setup-and-administration)" that says, "Enable Conditional Access" with a link to a new page for it. 
- Under the newly created "Enable Conditional Access" Page, we can include the following guidance: 

### Intro: 
Conditional access control capabilities in Azure Active Directory offer simple ways for you to secure resources in the cloud, including Viva Goals. For information about how conditional access works, see:
- [Azure Active Directory conditional access](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/)

### Requirements: 
In order for Viva Goals to appear as an app to be used for Conditional Access, you'll need to: 

1. Assign a Viva Goals license to at least one user
2. Have a Viva Goals org established 

### Steps to Enable Conditional Access:
1. Sign in to the Azure portal as a Conditional Access Administrator, Security Administrator, or Global Administrator.
2. Browse to Azure Active Directory > Security > Conditional Access.
3. Select New policy and give your policy a name.
4. Under Assignments, select Users or workload identities and choose who you want to apply this policy to. For example, you can select All users or specific groups of users.
5. Under Cloud apps or actions, select Viva Goals as the target of the policy. You can also select other apps that you want to include or exclude from this policy.
6. Under Conditions, select any criteria that you want to use to trigger this policy. For example, you can select Device platforms, Locations, Client apps, Device state, etc.
7. Under Access controls, select what action you want to take when this policy is triggered. For example, you can select Block access or Grant access with additional requirements such as multi-factor authentication.

**Comment by dariomws** [comment]
@RaSanders-MSFT, what do you think about this improvement? I cannot create new articles so I need your support here. Thank you both!

**Comment by RaSanders-MSFT** [comment]
Hey All!

Thank you for bringing this to my attention. Please fill out this form (select "content" as the answer to question 1) so we can add this request to our queue and have our PMs review the content: [Viva Goals Insights Form](https://teams.microsoft.com/l/entity/81fef3a6-72aa-4648-a763-de824aeafb7d/_djb2_msteams_prefix_3864951736?context=%7B%22subEntityId%22%3Anull%2C%22channelId%22%3A%2219%3Ac0817f76742e410987408499446b4eab%40thread.tacv2%22%7D&groupId=3c0ad314-4268-46d1-9502-1eb28349f765&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&allowXTenantAccess=false)

**Comment by RaSanders-MSFT** [comment]
Sorry about that, it should have opened the form tab in the group chat. Here is the link to the form directly: Customer Insights Form<https://forms.office.com/Pages/ResponsePage.aspx?Host=Teams&lang=%7Blocale%7D&groupId=%7BgroupId%7D&tid=%7Btid%7D&teamsTheme=%7Btheme%7D&upn=%7Bupn%7D&id=v4j5cvGGr0GRqy180BHbRxTTCjxoQtFGlQIesoNJ92VUQVpIVUtKTDhDMkZDSUtCVDE2TUY2NURXRiQlQCN0PWcu>

Rachelle Sanders
Program Manager
***@***.***

[Microsoft Logo]
________________________________

**Comment by soyalejolopez** [comment]
Thanks Rachelle. This one is not actually tied to a particular customer, which is a requirement for the form you shared. This is more of a documentation improvement.

Will ping you in Teams since this might be an opportunity to partner with Loreen's team as well. I was hoping this one would be a quick update. Typically for larger updates, I reach out to Loreen and her content form. I'll share more in Teams.
________________________________

**Comment by soyalejolopez** [comment]
Submitted 👍 Also pinged in Teams with more information on potential opportunity to align Viva content update requests using the form that Loreen's team uses for the other Viva apps.
________________________________

**Comment by collinscs** [comment]
@RaSanders-MSFT I just left a comment on feedback forum for the Viva Goals but not sure if it would reach you - I was wondering if someone would be willing to discuss with me the usage of Viva Goals at the national lab. Since it is not yet available to GCC tenant, I was wondering if there are other options available, perhaps through Conditional Access. We had previously been approved to use Ally.io.  Thanks!

**Comment by dariomws** [comment]
@soyalejolopez, thank you for submitting feedback. We understand that this issue has been resolved or it's in progress. Please follow-up this internally.

Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@collinscs, if you are a MS employee, please follow-up this internally. Thanks!

**Comment by soyalejolopez** [comment]
Hi @dariomws , can we re-open this issue please? We're getting feedback that the manner in which the article was updated is causing confusion. 

Would it be possible to implement the update as per our note above? That should help clarify. Thanks in advance 

![image](https://github.com/MicrosoftDocs/Viva/assets/28953579/a569e17e-56fd-4dcd-8728-1c6a7c0dcead)
