### ISSUE TITLE
Viva Insights Azure AD attributes synced to Advanced Insights to be increased from 3 to 5

### ISSUE THREAD

**Issue by vstanche** [MicrosoftDocs/Viva#520]
Hello Team,

Based on ICM ticket 364439416 and update from Engineer Siong Kong (siongkong_debug)

And based on Viva Insights community post:

https://community.vivainsights.microsoft.com/t5/Advanced-insights/AAD-data-source-attributes/m-p/2636/emcs_t/S2h8ZW1haWx8bWVudGlvbl9zdWJzY3JpcHRpb258TERURVJaOUk5WjQ4Wkl8MjYzNnxBVF9NRU5USU9OU3xoSw#M528

Replied by Darion Mannie

The below text:

_Azure Active Directory automatically syncs with the advanced insights app and provides data for the PersonId, ManagerId and Organization attributes._ 

Under about data sources

Need to be changed to

Azure Active Directory automatically syncs with the advanced insights app and provides data for the PersonId, ManagerId, Organization, Domain and Timezone attributes. Domain will be based on the email address value of the user in AAD and time zone is sycend from the Outlook settings.

Please advise if ok

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 234bafd9-77dd-1bb5-ef12-8b4c0b2613be
* Version Independent ID: 234bafd9-77dd-1bb5-ef12-8b4c0b2613be
* Content: [Organizational data overview](https://learn.microsoft.com/en-us/viva/insights/advanced/admin/org-data-overview)
* Content Source: [Viva/insights/advanced/admin/org-data-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/advanced/admin/org-data-overview.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears on any PRs or issues you submit—guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html. 

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=<alias>

**Comment by vstanche** [comment]
Hello All

Any update please?
