### ISSUE TITLE
Does it send a copy to recipient's manager?

### ISSUE THREAD

**Issue by lee-jennifer-ms** [MicrosoftDocs/Viva#521]
Does it send a copy to recipient's manager?

It's not clear from the UI if the praise only gets sent to the person or if their manager also gets a copy (the way the Kudos app did). It would be great if it did send a copy to the recipient's manager, and if so, something in the app UI informing people of that, the way the Kudos app did.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
