### ISSUE TITLE
When will Briefing be returned?

### ISSUE THREAD

**Issue by PB-Ryan** [MicrosoftDocs/Viva#522]
Looking for information regarding Viva Insights daily briefing - Web help file says this was disabled in Jan of 23, what is timeline for reintroduction of this feature?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
