### ISSUE TITLE
Will Viva Insights service plan users receive Schedule send suggestions in Teams chat?

### ISSUE THREAD

**Issue by TAKA-SHU** [MicrosoftDocs/Viva#523]
Will users with an assigned Viva Insights service plan (included in Office 365 E1/E3, Microsoft 365 E3) receive suggestions for sending scheduled Teams chat?
Please clarify whether or not they will, and (if so) what the limit is.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 07802a8e-5264-16e5-5d02-563d86fd9c30
* Version Independent ID: 07802a8e-5264-16e5-5d02-563d86fd9c30
* Content: [Schedule send suggestions in Teams chat](https://learn.microsoft.com/en-us/viva/insights/personal/teams/schedule-send)
* Content Source: [Viva/insights/personal/teams/schedule-send.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/teams/schedule-send.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
