### ISSUE TITLE
HubSpot wrong data

### ISSUE THREAD

**Issue by arlogilbert** [MicrosoftDocs/Viva#527]
HubSpot integration has a date range of Jan 1 2023 - Dec 31 2023 but instead it is pulling in all historical data, resulting in inaccurate OKR completion %s.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7074f9af-0e5c-279a-8ea1-c2d1efc5e37d
* Version Independent ID: 7074f9af-0e5c-279a-8ea1-c2d1efc5e37d
* Content: [Microsoft SQL Server integration](https://learn.microsoft.com/en-us/viva/goals/ms-sql-server-integration)
* Content Source: [Viva/goals/ms-sql-server-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/ms-sql-server-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by dariomws** [comment]
@arlogilbert - thank you for submitting feedback. 

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome, let me know if it can be called out in the docs. 

Please follow this link to contact support for business products: https://docs.microsoft.com/office365/admin/contact-support-for-business-products. 

Please keep us posted here on the resolution to feed whatever information you discover into the content.
