### ISSUE TITLE
Add note that new topics must be created in English by default

### ISSUE THREAD

**Issue by sinansuer** [MicrosoftDocs/Viva#529]
CJ Tan from the Product Group confirmed that English is always the default language for the Topics Center. 

This documentation currently states that "A topic page must be created and curated in the tenant's default language before it can be curated to a different language using the Multilingual feature in Viva Topics."  

It needs to be updated to mention that new topics must be created in English first, regardless of the tenant's default language.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37a2ec21-8c88-cbbe-0053-ef3a579ea71f
* Version Independent ID: 37a2ec21-8c88-cbbe-0053-ef3a579ea71f
* Content: [Curate Multilingual topics in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/curate-a-topic-in-multilingual)
* Content Source: [Viva/topics/curate-a-topic-in-multilingual.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/curate-a-topic-in-multilingual.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @ruthholls
* Microsoft Alias: **ruthhollands**

**Comment by get-itips** [comment]
Hello @sinansuer 
I'm working on this.

**Comment by get-itips** [comment]
Fixed in https://github.com/MicrosoftDocs/Viva/commit/fbcdb1a0c1fb6807e81835a9512a75bca29ad1c0
Thanks for your feedback!
