### ISSUE TITLE
Outdated doc https://learn.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/manage-policy-tips?source=docs

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/Viva#530]
Hello,

Please correct this doc: https://learn.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/manage-policy-tips?source=docs
These settings are no longer edited in EAC, it is moved to Compliance Center.

**Comment by get-itips** [comment]
Hello @bozenektoja 
You opened an issue in the Viva repository, Exchange content can't be created issues against anymore.
