### ISSUE TITLE
Leadership, AMA and Analitics not available even with Viva Suite assigned license in Feature Management

### ISSUE THREAD

**Issue by amdf777** [MicrosoftDocs/Viva#537]
Leadership Corner, Leadership identification and audiences, Campaings and Analitics are not available in Feature Management even with Viva Suite assigned license.
There are only Answers, Rewards and Storyline buttons. 
Permissions - Global Admin, Yammer Admin
Licenses/Apps - Viva Suite, Viva Engage Core + Office 365 E5 + Yammer enterprise 
What can be the reason?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dc47f6e-1e2f-6c6b-2bbd-3aad60910488
* Version Independent ID: 0dc47f6e-1e2f-6c6b-2bbd-3aad60910488
* Content: [Identify leaders and manage audiences in Viva Engage](https://learn.microsoft.com/en-us/viva/engage/leadership-identification)
* Content Source: [Viva/engage/leadership-identification.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/engage/leadership-identification.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @mamiepjohnson
* Microsoft Alias: **mamiejohnson**

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
