### ISSUE TITLE
Viva connection desktop weird behaviour

### ISSUE THREAD

**Issue by ymaldor1** [MicrosoftDocs/Viva#538]
Hi,

On viva connection desktop version, from microsoft.teams.com app, the behaviour when clicking on a news feed is weird.
For context, I'm using a global admin account on a cdx viva tenant and using the app on Microsoft Edge.

Steps to reproduce : 
-Open teams.microsoft.com
-head to viva connection app
-Click one of the feed item (this gets you to a new tab into SharePoint site)
-Head back to the Teams.microsoft.com tab

Now, the teams.microsoft app also opened the site, however, the news is in edit mode (see update news button), but with the edit button showing still. The URL doesn't specify ?mode=edit, the page is just in both edit and non-edit mode somehow. See picture below :
![image](https://user-images.githubusercontent.com/126237455/221133050-9c6e8b87-a1e0-47d9-b4a2-5823d906b7d3.png)

So viva opens the news article in both a new tab AND in the app, but in the app the page itself is in in a weird state. When not admin on the news article, the page doesn't show in the weird editable non-edit mode, but it still opens it both in new tab and in app.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
