### ISSUE TITLE
Please include details on how the Home Feed works in Viva Engage 

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#539]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

We currently don't have much details on how the "Home Feed" for Viva Engage works. Please include more specifics on how the algorithm works. As an example, here's what we have for the Connections Feed and how that works, which is very helpful. 

https://review.learn.microsoft.com/en-us/viva/connections/faqs-viva-connections-feed?branch=main

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d7251692-b319-16ec-fb03-1a73e54f8943
* Version Independent ID: d7251692-b319-16ec-fb03-1a73e54f8943
* Content: [Viva Engage admin key concepts](https://review.learn.microsoft.com/en-us/viva/engage/admin-key-concepts?branch=main)
* Content Source: [Viva/engage/admin-key-concepts.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/engage/admin-key-concepts.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @dwhitfield233
* Microsoft Alias: **v-whitfieldd**

**Comment by soyalejolopez** [comment]
Hi @dwhitfield233 , it seemed the most fitting given the options, but honestly a separate article dedicated just to this topic much like the Connections referenced article would be ideal. Currently, we don't have those details for Viva Engage.

**Comment by get-itips** [comment]
Checked internally and it was decided to leave as is as request is covered in other articles.
