### ISSUE TITLE
Partner eCDN supported Teams live event at Viva Engage?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#540]
[Enter feedback here]
Some customers want to have Teams live events on Viva Engage. This case, Partner eCDN is support?
<reference>
https://learn.microsoft.com/en-us/microsoftteams/teams-live-events/plan-for-teams-live-events#teams-live-events

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b340d5c1-d551-c9b7-dfae-289d5996d638
* Version Independent ID: b340d5c1-d551-c9b7-dfae-289d5996d638
* Content: [Set up Viva Engage](https://learn.microsoft.com/en-us/viva/engage/setup)
* Content Source: [Viva/engage/setup.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/engage/setup.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @v-jebizie
* Microsoft Alias: **v-jebizie**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
