### ISSUE TITLE
Focus Tutorial - Update link to use new domain

### ISSUE THREAD

**Issue by jonquandt** [MicrosoftDocs/Viva#542]
For the link to the article on [How to finally kill the useless, recurring meeting](https://insights.office.com/digital-transformation/how-to-finally-kill-the-useless-recurring-meeting/), the insights.office.com domain leads to a security certificate error in Firefox. IT appears that the domain has been replaced with https://workplaceinsights.microsoft.com.

Could the link be updated in this article?

See https://learn.microsoft.com/en-us/viva/insights/tutorials/gm-focus#cancel-recurring-meetings

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 263a9dc6-2729-ae83-572e-48d4caf6084f
* Version Independent ID: 40329976-c51e-d90a-e4ac-d9bbab1c3c43
* Content: [Best practices for focus time](https://learn.microsoft.com/en-us/viva/insights/tutorials/gm-focus)
* Content Source: [Viva/insights/tutorials/gm-focus.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/tutorials/gm-focus.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by get-itips** [comment]
Thanks for your feedback, I just noticed you already created a PR
