### ISSUE TITLE
wrong admin roles described for topics

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#544]
- There is no role named "Viva Topcis Admin"
- The Knowledge Admin role is missing for Viva Topics
- There is a role "Knowledge Manager" in Microsoft 365 but this has nothing to do with the knowledge manager. The knowledge admin grants the permission to manage topics in the M365 admin center but this is not an admin role. 
- The knowledge administrator does not necessarily need to be a global admin, sharepoint admin or group admin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17dd3520-1112-6c4b-d131-bca4194197fd
* Version Independent ID: 17dd3520-1112-6c4b-d131-bca4194197fd
* Content: [Admin roles and tasks in Microsoft Viva](https://learn.microsoft.com/en-us/viva/microsoft-viva-admin-roles)
* Content Source: [Viva/microsoft-viva-admin-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/microsoft-viva-admin-roles.md)
* Service: **viva**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by LoreenLa** [comment]
Topic has been updated with information from product team.

From: LennartaeHoefer ***@***.***>
Sent: Friday, March 3, 2023 9:22 AM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Loreen La Penna ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Viva] wrong admin roles described for topics (Issue #544)


  *   There is no role named "Viva Topcis Admin"
  *   The Knowledge Admin role is missing for Viva Topics
  *   There is a role "Knowledge Manager" in Microsoft 365 but this has nothing to do with the knowledge manager. The knowledge admin grants the permission to manage topics in the M365 admin center but this is not an admin role.
  *   The knowledge administrator does not necessarily need to be a global admin, sharepoint admin or group admin

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 17dd3520-1112-6c4b-d131-bca4194197fd
  *   Version Independent ID: 17dd3520-1112-6c4b-d131-bca4194197fd
  *   Content: Admin roles and tasks in Microsoft Viva<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fviva%2Fmicrosoft-viva-admin-roles&data=05%7C01%7Cloreenl%40microsoft.com%7C7a83e53e856641867f8a08db1c0bc9af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134609194417405%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2Cv6TrqFp%2F5w5MoGmLRl3qbKzMcDX%2FWKf7JCcJA8Sts%3D&reserved=0>
  *   Content Source: Viva/microsoft-viva-admin-roles.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-WorkplaceAnalytics%2Fblob%2Fpublic%2FViva%2Fmicrosoft-viva-admin-roles.md&data=05%7C01%7Cloreenl%40microsoft.com%7C7a83e53e856641867f8a08db1c0bc9af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134609194417405%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fyz%2BX%2FvyBi4NYYDRzcxuAP1Dps9NT4ueVQ4FaYlh23M%3D&reserved=0>
  *   Service: viva
  *   GitHub Login: @LoreenLa<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLoreenLa&data=05%7C01%7Cloreenl%40microsoft.com%7C7a83e53e856641867f8a08db1c0bc9af%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638134609194417405%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NCvHERH9dFoEaGaB1vS4NggUVDpZMnl4gNj4IUgVafM%3D&reserved=0>
  *   Microsoft Alias: loreenl

**Comment by get-itips** [comment]
Thank you for sharing the information @LoreenLa
