### ISSUE TITLE
learning paths = premium feature

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#545]
It would be helpful to place a note that the creation of learning paths is a premium feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c37e9f68-03c6-edb7-533a-fcfe4b0018d3
* Version Independent ID: c37e9f68-03c6-edb7-533a-fcfe4b0018d3
* Content: [Creating Learning paths in Viva Learning](https://learn.microsoft.com/en-us/viva/learning/creating-learning-paths)
* Content Source: [Viva/learning/creating-learning-paths.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/creating-learning-paths.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by Charles-D-D** [comment]
Finally get the info! Thanks. 
Seriously, it's not even in the blog post.. I finally bought a license to discover it's a premium feature..
Even the Microsoft Support have no clue :s

**Comment by get-itips** [comment]
Article has been updated. Thanks for your feedback.
