### ISSUE TITLE
Indicator on app in TEAMS or replicate notification alerts to app on menu

### ISSUE THREAD

**Issue by bwbrandiwoodson** [MicrosoftDocs/Viva#546]
Would be helpful letting users know of new alerts on the app in TEAMS app on the actual cica enage menu item itself vs making users have to remember to open the VE app to check for alerts. 

I couldn't  find a way to do this

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
