### ISSUE TITLE
How long does it take for the role to be effective

### ISSUE THREAD

**Issue by vstanche** [MicrosoftDocs/Viva#549]
Hello Team,

A lot of customers are asking what is the recommended allocated time between the time stamp when the role is assigned and when it can be effectively used.

Is it possible to add this information to the article, it will be very valuable to know

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e357945-8c53-5c40-df52-4bda11048da0
* Version Independent ID: 7e357945-8c53-5c40-df52-4bda11048da0
* Content: [Roles in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/topic-experiences-roles)
* Content Source: [Viva/topics/topic-experiences-roles.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/topic-experiences-roles.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @ruthholls
* Microsoft Alias: **ruthhollands**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
