### ISSUE TITLE
Out of date image in To access topics management settings:

### ISSUE THREAD

**Issue by nikki-c** [MicrosoftDocs/Viva#550]
The image in the section To access topics management settings: point 2 is out of date. Here is the updated image 
![image](https://user-images.githubusercontent.com/69439002/225093719-4f0af84d-646e-4013-949a-2c2efa632a62.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e35fad7f-62a3-885b-c5fc-4be15ceeb7d7
* Version Independent ID: e35fad7f-62a3-885b-c5fc-4be15ceeb7d7
* Content: [Change the name of the topic center in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/topic-experiences-administration)
* Content Source: [Viva/topics/topic-experiences-administration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/topic-experiences-administration.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @ruthholls
* Microsoft Alias: **ruthhollands**

**Comment by get-itips** [comment]
Image updated in https://github.com/MicrosoftDocs/Viva/commit/76a0876d0f7daea8d3b89e87b7727c3108687d38
Thanks!
