### ISSUE TITLE
Not Adequately Tested

### ISSUE THREAD

**Issue by sfbunikent** [MicrosoftDocs/Viva#552]
Just an observation on all the threads here suggesting improvements and removing bugs, it just seems to me this product has not been adequately tested? Is this usual? How many issues are arising here in relation to other products? Are you happy with the level of service? When launching a service about productivity of time, is it right to do this in an unfinished state? It would not happen in other sectors, healthcare for example, where 3rd party validation would be needed for a product that aims to improve mental wellbeing?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
