### ISSUE TITLE
Add a Note OR Line: About the after experience of the Viva Connections app PIN on Microsoft Teams side 

### ISSUE THREAD

**Issue by anaritaroque** [MicrosoftDocs/Viva#554]
Hello Team, there has been reported a lot of misunderstand about Pin the Viva Connections apps in Microsoft Teams. Our customers and even some of our Microsoft Teams colleagues, think that Pin the Viva Connections apps in Teams, will make default design behavior's of Microsoft Teams change. 

Since "Microsoft Viva Connections is your gateway to a modern employee experience", so this is where you will find your intranet.  
They think that after Pin the Viva Connections apps in Teams Admin Center, will make every time they open now Microsoft Teams to have Viva Connections has default experience and not the chat experience in Teams anymore. Causing a lot of misunderstand and confusion about what "Pin the app" for Viva Connections really means.

Therefore, in this sense if we could just ad a line or a note saying something like: **Please note after Pin the Viva Connections app in Teams, it won´t change the default Microsoft Teams design experience. Once you open Microsoft Teams, Viva Connections will be pin on the left side bar, and you still need to selected it to open the Viva Connections app in Microsoft Teams.**  

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3adb907a-df77-715b-38ea-01064c6c451f
* Version Independent ID: 3adb907a-df77-715b-38ea-01064c6c451f
* Content: [Add the Viva Connections app in the Teams admin center](https://learn.microsoft.com/en-us/viva/connections/add-viva-connections-app)
* Content Source: [Viva/connections/add-viva-connections-app.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/connections/add-viva-connections-app.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Thanks so much for bringing this up. I just submitted a separate PR that adds a note and captures the sentiment you suggested. We should see this updated around 5pm PT.

**Comment by anaritaroque** [comment]
Hello! Thank you for allowing me to contribute into our Microsoft documentation! I believe this can bring more clarity between how our two products (Microsoft Viva Connections and Microsoft Teams) work/interact together with the Pin the app functionality.
