### ISSUE TITLE
The option to enable integrations is not there while accessing the admin page Viva Goals teams application 

### ISSUE THREAD

**Issue by bozenektoja** [MicrosoftDocs/Viva#555]
[Enter feedback here]

The button "settings" is not there when accessing Viva Goals teams app Home
![image](https://user-images.githubusercontent.com/71028589/226548566-a27eb72d-bd4d-40ce-b443-8d2678851cdf.png)
![image](https://user-images.githubusercontent.com/71028589/226548609-ce5ff6d7-a260-4f77-a7b1-58d345716334.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 268af470-0220-313e-685b-2c11cf0286b4
* Version Independent ID: 268af470-0220-313e-685b-2c11cf0286b4
* Content: [Enable Integrations in Viva Goals](https://learn.microsoft.com/en-us/viva/goals/vg-integrations-administration-overview)
* Content Source: [Viva/goals/vg-integrations-administration-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/vg-integrations-administration-overview.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @rasanders
* Microsoft Alias: **rasanders**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
