### ISSUE TITLE
Microsoft Viva Insights for shared mailboxes

### ISSUE THREAD

**Issue by kval07** [MicrosoftDocs/Viva#561]
Viva Insights does not report about email messages sent from a shared mailbox. Is this a feature being considered? I can't send companywide emails from my individual email address, so I can't track open rate.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by kval07** [comment]
Hi @scanum - This isn't a issue that needs to be resolved, but rather a feature Microsoft doesn't currently offer. Is your recommendation still the way to go?
