### ISSUE TITLE
Add steps about adding column ContentTitle in the Metadata section

### ISSUE THREAD

**Issue by vstanche** [MicrosoftDocs/Viva#563]
It is now possible to add column Content title and we can add the below steps for that under the steps for ContentDescription in the metadata section as follows:

To add a title column to the document library page, follow these steps:

1. Follow the initial steps to create a column.
2. Choose Multiple lines of text.
3. Name the column ContentTitle.
4. Add custom title for each item. If no title is supplied, Viva Learning will pick the file name as the title.

Note:The changes will take 24-48 hrs for the change to reflect in Viva Learning.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source#metadata)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by dariomws** [comment]
If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears on any PRs or issues you submit—guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html. 

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=vstanche

**Comment by dariomws** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
