### ISSUE TITLE
Clarify M365 admin role under Choose a rollout scenario section

### ISSUE THREAD

**Issue by vstanche** [MicrosoftDocs/Viva#565]
In the Choose a rollout scenario it says:

A Microsoft 365 admin can implement any of these scenarios either by using PowerShell or by using the Microsoft 365 admin center. Typically, admins use the admin center to broadly configure Viva Insights for most or all users, and they use PowerShell to set specific configurations for select users.

Can it be clarified what type of M365 admin the user needs to have because User administrator does not work for example?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 412cc99c-71d3-b2ad-f2e6-38b6270522ed
* Version Independent ID: adf90afb-7fe5-9c46-0992-e030b8b995e1
* Content: [Personal insights deployment guide](https://learn.microsoft.com/en-us/viva/insights/personal/setup/deployment-guide)
* Content Source: [Viva/insights/personal/setup/deployment-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/setup/deployment-guide.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Hello @vstanche 
How are you?
Have you seen this article?
https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/assign-admin-roles

**Comment by get-itips** [comment]
@scanum Closing, can be re-opened.

**Comment by vstanche** [comment]
Yes thank you

I am wondering out of curiosity. What does it take to be included as author?
Thank you

Best of Regards

Veselin

FastTrack EMEA Viva SME Team
________________________________
