### ISSUE TITLE
Innu-aimun language support

### ISSUE THREAD

**Issue by tshakapeshjg** [MicrosoftDocs/Viva#568]
Hi,  I am initiating a request that might take a while about supporting a new language.  I would be curious to learn and/or get information on how can a new language (Innu-aimun,  Indigenous from far North-East of america) be supported.  We have a dictionary and a large amount of data we could use to create such support.  Visit : [dictionnaire.innu-aimun.ca](https://dictionnaire.innu-aimun.ca/Words) to get an idea.  You can also visit the institute site at  : [www.tshakapesh.ca](https://www.tshakapesh.ca/) (but its in French).

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
