### ISSUE TITLE
Focus Time - Title Change

### ISSUE THREAD

**Issue by kennytbmgf** [MicrosoftDocs/Viva#569]
Is there an option available to change 'Focus Time' to 'Focus time - Please Reach out to Schedule' in the Focus Plan webpage? (rather than changing manually each occurrence in Outlook Calendar)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
