### ISSUE TITLE
Viva Connection Dashboard background doesn't change with section background.

### ISSUE THREAD

**Issue by SergeyOreshin** [MicrosoftDocs/Viva#572]
There are a statement in the official documentation:

> The Dashboard web part can be used in sections with a colored background: When editing a section, you can change the background of the section and the cards of the Dashboard will have a different color from that background.

It haven't. It always stays with white rectangle on the background. Which looks not great with strong background shading.
This has changed with latest updates, previously it worked as expected.

**Comment by scanum** [comment]
@SergeyOreshin Thanks for the feedback. Could you please link the documentation?

**Comment by SergeyOreshin** [comment]
Here is the link. [https://learn.microsoft.com/en-us/viva/connections/use-dashboard-web-part-on-home-site#additional-information](https://learn.microsoft.com/en-us/viva/connections/use-dashboard-web-part-on-home-site#additional-information)

But I don't ask to fix a documentation, this feature should be in Dashboard and now it does not work.

**Comment by get-itips** [comment]
Hello @SergeyOreshin 
As we are limited to documentation fixes and improvements, this fit better in the feedback resource for viva connections https://feedbackportal.microsoft.com/feedback/forum/5092ec4b-1d1c-ec11-b6e7-0022481f8472
