### ISSUE TITLE
Fix indents in Viva Connections app bar in Teams

### ISSUE THREAD

**Issue by SergeyOreshin** [MicrosoftDocs/Viva#573]
It looks really uncomfortable and too heap to use. Give more space. 

<img width="381" alt="Screenshot 2023-04-06 at 17 26 57" src="https://user-images.githubusercontent.com/128693227/230430061-d54ea1d6-67ba-4c56-83bf-7bf850b38b46.png">

<img width="388" alt="Screenshot 2" src="https://user-images.githubusercontent.com/128693227/230429655-3c471ff5-88a9-401a-b169-ecc64b1a04d7.png">

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
