### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JohnPobedinsky** [MicrosoftDocs/Viva#574]
[Enter feedback here]
Does Schedule Send still work if your PC is turned off at the time of the scheduled message delivery?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49270ffb-610d-7a8b-574a-f103986cfa33
* Version Independent ID: 49270ffb-610d-7a8b-574a-f103986cfa33
* Content: [Schedule send with Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/use/schedule-send)
* Content Source: [Viva/insights/personal/use/schedule-send.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/use/schedule-send.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
