### ISSUE TITLE
Reference to Effective Meetings section in VITA obsolete.

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/Viva#580]
[With the new look and feel change to the Viva Insights in Teams app - this tab is no longer available.  Will need to update to refer to Productivity tab. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cb7a248-e7fd-aba7-fa87-d8e2875f520b
* Version Independent ID: 4cb7a248-e7fd-aba7-fa87-d8e2875f520b
* Content: [Meeting effectiveness surveys in Viva Insights](https://learn.microsoft.com/en-us/viva/insights/personal/teams/meeting-effectiveness-surveys#settings)
* Content Source: [Viva/insights/personal/teams/meeting-effectiveness-surveys.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/teams/meeting-effectiveness-surveys.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Hello @karleesm 
The article in Learn doesn't exists anymore and redirects to a support article.
Thanks for your feedback,
