### ISSUE TITLE
Images used in viva topics documentation do not reflect the current state of viva topics in the M365 admin center.

### ISSUE THREAD

**Issue by UdokaVrede** [MicrosoftDocs/Viva#581]
[The images used in demonstrating the setup of viva topics from m365 org settings option under settings, doesn't reflect the same naming convention used in the admin center ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d27e1f6-9c0d-3264-0d0c-31479c102981
* Version Independent ID: 7d27e1f6-9c0d-3264-0d0c-31479c102981
* Content: [Topic center overview in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/topic-center-overview)
* Content Source: [Viva/topics/topic-center-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/topics/topic-center-overview.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @ruthholls
* Microsoft Alias: **ruthhollands**

**Comment by UdokaVrede** [comment]
Happy to update this with snapshots from my demo tenant.

**Comment by get-itips** [comment]
Hello @UdokaVrede 
Screenshots of Viva Topics option under Settings have been updated recently.

**Comment by UdokaVrede** [comment]
Perfect, thank you

**Comment by get-itips** [comment]
Thank you for your feedback
