### ISSUE TITLE
Reference to MyAnalytics - now obsolete?

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/Viva#582]
[Thinking that all the references to MyAnalytics here is now all obsolete?]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60b4d68f-17e0-d538-6095-70f44e214bbf
* Version Independent ID: 2149a913-8877-fff0-5b08-050fb5adbbde
* Content: [Plans and environments for personal insights](https://learn.microsoft.com/en-us/viva/insights/personal/overview/plans-environments)
* Content Source: [Viva/insights/personal/overview/plans-environments.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/personal/overview/plans-environments.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Hello @karleesm I'm working on this
