### ISSUE TITLE
Native Mode migration step by step guide end user experience gaps

### ISSUE THREAD

**Issue by vstanche** [MicrosoftDocs/Viva#584]
Hello All

In the below article

https://learn.microsoft.com/en-us/yammer/configure-your-yammer-network/native-mode-step-by-step-guide

Section

Tracking Alignment Tool Progress

It says

The Alignment Tool will run in the background of your system and should not cause any noticeable impact for end users.

Can you please help by adding some more clarification there, because the customers are raising the questions:

Will the end user experience with Yammer/Viva Engage be entirely uninterrupted?
What will happen if content is being added/updated/removed during the migration process, how is this going to align on the completion phase?
After the migration is completed, can we presume that the end user will not be asked to reauthenticate or anything like that?
Can end users expect any kind of notifications - Yammer/Viva Engage/Outlook - during the process

**Comment by tiburd** [comment]
@vstanche 

For the article that you're providing feedback, we recommend checking the Microsoft Feedback Forum and submitting it there if it has not already been submitted:
- [Microsoft Viva Engage](https://feedbackportal.microsoft.com/feedback/forum/bd6e5ec2-3f1c-ec11-b6e7-0022481f8472)

Another option is visit the [Yammer help center](https://support.microsoft.com/en-us/office/yammer-help-center-8663922d-8f76-47c2-827a-ee86e8cac00f).

Thanks!
