### ISSUE TITLE
Incorrect guidance on removed feature, create a team has been removed from UI after refresh

### ISSUE THREAD

**Issue by saashby** [MicrosoftDocs/Viva#593]
This is now incorrect, you can not add a custom team or create and manage a team in the new refresh UI for the Viva Insights Teams app

_Manage your team
As a licensed Viva Insights user, you can create a team and view insights about them within the Viva Insights app. You’ll be able to add or confirm members on the Home page as explained below, but you can also make changes to your team on the Teamwork habits page.

If you’re not a manager, Viva Insights prompts you to Create your team._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e76af468-1860-354e-710f-a62fe998b314
* Version Independent ID: e76af468-1860-354e-710f-a62fe998b314
* Content: [Teamwork habits in Viva Insights](https://learn.microsoft.com/en-us/viva/insights/org-team-insights/reference/teamwork-habits)
* Content Source: [Viva/insights/org-team-insights/reference/teamwork-habits.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/org-team-insights/reference/teamwork-habits.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by lilyolason** [comment]
Hi @saashby -- thank you for submitting. The Teamwork habits content is retired and redirects to our current Team insights documentation.
