### ISSUE TITLE
Include '.' for ContentAuthor?

### ISSUE THREAD

**Issue by gdackerm** [MicrosoftDocs/Viva#595]
Looks like a typo.  For the custom content values, only 'ContentAuthor' includes the period '.' in the highlighted text.  We don't need to include that period in the SharePoint column, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Thanks for your feedback!
