### ISSUE TITLE
Adding the impact of encryption by sensitivity labels to Viva Topics

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#597]
It would be helpful to add a description to this page what the impact would be if documents are encrypted by sensitivity labels. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55f84eef-010c-a39e-c644-92bbce8b0801
* Version Independent ID: 55f84eef-010c-a39e-c644-92bbce8b0801
* Content: [Manage topic discovery in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/topic-experiences-discovery#exclude-resources-based-on-sensitivity-labels)
* Content Source: [Viva/topics/topic-experiences-discovery.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/topics/topic-experiences-discovery.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by daisyfell** [comment]
added a note to the article, which should go live soon
