### ISSUE TITLE
Missing Info/Note

### ISSUE THREAD

**Issue by emma-606** [MicrosoftDocs/Viva#600]
Missing link to definition of non collaboration email

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77d6b9ae-428f-2fe1-b716-30e0b5e728cd
* Version Independent ID: 77d6b9ae-428f-2fe1-b716-30e0b5e728cd
* Content: [Metric rules in Viva Insights](https://learn.microsoft.com/en-us/viva/insights/advanced/analyst/metric-rules)
* Content Source: [Viva/insights/advanced/analyst/metric-rules.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/analyst/metric-rules.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Hello @emma-606 
To understand better, can you point me to the right sentence that you are talking about? Thank you!

**Comment by nkato0503** [comment]
Can you tell me which page you are referring to and what is the URL?
It may just be my unfamiliarity with GitHub.

**Comment by scanum** [comment]
@get-itips

**Comment by get-itips** [comment]
@scanum closing as no response from issue author
