### ISSUE TITLE
Guidance missing?

### ISSUE THREAD

**Issue by DaleRNorman** [MicrosoftDocs/Viva#601]
There doesn't appear to be information on how to get to the console referenced in the article.
https://analysis.insights.viva.office.com/admin/organizationalData

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba8b311a-358e-7ec9-d7ae-fe0aaff4ea0e
* Version Independent ID: ba8b311a-358e-7ec9-d7ae-fe0aaff4ea0e
* Content: [Upload organizational data (first upload)](https://learn.microsoft.com/en-gb/viva/insights/advanced/admin/upload-org-data-first)
* Content Source: [Viva/insights/advanced/admin/upload-org-data-first.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/admin/upload-org-data-first.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by get-itips** [comment]
Article was updated.
