### ISSUE TITLE
Access to the Viva Goals Admin Portal has moved

### ISSUE THREAD

**Issue by olivjat** [MicrosoftDocs/Viva#603]
Documentation on managing integrations needs to be updated as steps 2, 3 and 4 are now innacurate.
Admin has to click on the Admin entry on the left pane and select Viva Goals admin portal to get access to the integrations management interface for the entire organization

**Comment by scanum** [comment]
Hi @olivjat thanks for the feedback. Could you please help us by linking the documentation you are referring to? Appreciate your help.

**Comment by olivjat** [comment]
https://learn.microsoft.com/en-us/viva/goals/vg-integrations-administration-overview

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by get-itips** [comment]
Thanks for your feedback!
