### ISSUE TITLE
Topics before published used SharePoint Online storage?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#604]
[Enter feedback here]
Hi, team!

Topics before published not use SharePoint Online storage. Is my understanding correct? I'm afraid of using SPO storage when Viva Topics make a lot of suggested topics.

best regards,
Daishi.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 721f924b-aca2-610f-21cb-55c1f83246fc
* Version Independent ID: 721f924b-aca2-610f-21cb-55c1f83246fc
* Content: [Manage topics in the topic center in Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/manage-topics)
* Content Source: [Viva/topics/manage-topics.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/topics/manage-topics.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
