### ISSUE TITLE
Heirachy is misleading

### ISSUE THREAD

**Issue by TehHammerCDN** [MicrosoftDocs/Viva#607]
The graphic shown depicts an Objective under a Key Result. Viva Goals does not permit child objects under a Key Result.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cab00ea2-6b26-4734-ec05-290eb3cd0700
* Version Independent ID: cab00ea2-6b26-4734-ec05-290eb3cd0700
* Content: [Understanding views in Viva Goals](https://learn.microsoft.com/en-us/viva/goals/understanding-views)
* Content Source: [Viva/goals/understanding-views.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/goals/understanding-views.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by TehHammerCDN** [comment]
![a](https://github.com/MicrosoftDocs/Viva/assets/97485477/ac0f095f-3ce5-4a47-ba72-68a5ff0ca021)

**Comment by dariomws** [comment]
Hi @TehHammerCDN, thank you for your feedback.

I'm replacing the picture with this one:
![image](https://github.com/MicrosoftDocs/Viva/assets/33589238/a406b6e8-0d81-4694-8b20-cfe37aaca8c2)

**Comment by RaSanders-MSFT** [comment]
Viva Goals does permit child objectives under a key result, however this function must be enabled by an admin and is not turned on by default. Changing the image makes sense since it represents the default experience more accurately.
