### ISSUE TITLE
Disable card action

### ISSUE THREAD

**Issue by a1mery** [MicrosoftDocs/Viva#612]
It says on the [Design your own card with a quick view](https://learn.microsoft.com/en-us/viva/connections/create-dashboard#design-your-own-card-with-a-quick-view) that you have to toggle to **On** the **Enable card action**.

Where can I find this toggle ? In my case it is on by default and I can't set it to **off**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 142c2405-1386-af8c-1f7b-1f96a424b8d0
* Version Independent ID: 142c2405-1386-af8c-1f7b-1f96a424b8d0
* Content: [Add, edit, and remove cards from the Viva Connections dashboard ](https://learn.microsoft.com/en-us/viva/connections/create-dashboard)
* Content Source: [Viva/connections/create-dashboard.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/connections/create-dashboard.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
