### ISSUE TITLE
Music out of tune

### ISSUE THREAD

**Issue by jammiefoy** [MicrosoftDocs/Viva#615]
It's ridiculous that I had to sign up for a GitHub account just to provide feedback.
The music that is supposed to calm/soothe in Lo-Fi AND the music that is meant to increase focus/productivity in Zoom Out is OUT OF TUNE. No one can relax or focus with bad music. Please remember that not all customers are blessed with up-to-date equipment or OS. 
I'm running 64-bit OS, Windows 10 Enterprise with Windows Feature Experience Pack 120.2212.4190.0. 
Is there a compatibility setting I'm overlooking?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
