### ISSUE TITLE
Rollout to all customers expected 

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#620]
See MC557823 
Rollout to all customers expected end of July 2023 not end of June. I guess June was the previous timeline. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Version Independent ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Content: [Set up Viva Connections in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/viva/connections/set-up-admin-center#step-2-assign-permissions)
* Content Source: [Viva/connections/set-up-admin-center.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/connections/set-up-admin-center.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @AtkinE
* Microsoft Alias: **evanatkin**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by LennartaeHoefer** [comment]
Please refer to MC557823. 

Updated June 5, 2023: We have updated the rollout timeline below. Thank you for your patience.

A new feature will be available soon for Viva Connections that enables you to create and manage multiple Connections experiences and home sites that are targeted to specific audiences for your organization through the Microsoft 365 admin center. This feature is ideal for subsidiaries and conglomerates that want to provide distinct, audience targeted experiences with relevant and personalized information, resources, and apps to their employees.

This message is associated with Microsoft 365 Roadmap ID [99916](https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=99916), [117421](https://www.microsoft.com/microsoft-365/roadmap?filters=&searchterms=117421)

When this will happen:

Targeted Release: We will begin rolling out this feature by mid-June 2023.

Standard Release: We will begin rolling out in late June and **expect to complete by late July.**
