### ISSUE TITLE
screenshot resolution

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#621]
some of the screenshots are really hard to read as the resolution is quite low. seems to be some compression has been in place. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Version Independent ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Content: [Set up Viva Connections in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/viva/connections/set-up-admin-center#step-2-assign-permissions)
* Content Source: [Viva/connections/set-up-admin-center.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/connections/set-up-admin-center.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @AtkinE
* Microsoft Alias: **evanatkin**

**Comment by get-itips** [comment]
Screenshots were updated after the creation of this issue.
Thank you.
