### ISSUE TITLE
My report manager manages over 3 teams, Peer organization means what teams?

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#626]
[Enter feedback here]
Hi, support teams.
Our customer wants to know Peer organization logic when report manager lead many teams. So I want to confirm specification about "Peer organization". 

[Premise]
・My report manager is Jon. I join HR division 1 now.
・Jon manages over than 3 teams what HR divison1, HR division 2, HR division 3, Sales team.

[Questions]
1. My report manager manages over 3 teams, Peer organization means what teams?

2. In this case, Can IT admin change  Peer organization for Jon?

Best regards,
Daishi.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fbdf94ed-af3b-8b1c-981f-142e62d45fba
* Version Independent ID: fbdf94ed-af3b-8b1c-981f-142e62d45fba
* Content: [Organization insights in the Viva Insights app](https://learn.microsoft.com/en-us/viva/insights/org-team-insights/org-insights)
* Content Source: [Viva/insights/org-team-insights/org-insights.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/org-team-insights/org-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
