### ISSUE TITLE
I would like to know the operation specifications when setting the Shared meeting plan in Viva Insights.

### ISSUE THREAD

**Issue by dshimogawa** [MicrosoftDocs/Viva#627]
[Enter feedback here]
Hi, support team!
One customer wants to setting the Shared meeting plan for a team in Viva Insights. This plan rule is start late 5 mins. If plan recipients schedule  meeting, this meeting set automatically starting 5 late mins? If they did not start Teams meeting late 5mins, Viva Insights system alert for plan recipients?

best regards,
Daishi.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bd1f1dc9-eaea-5578-a971-44414c01ea54
* Version Independent ID: bd1f1dc9-eaea-5578-a971-44414c01ea54
* Content: [Team insights](https://learn.microsoft.com/en-us/viva/insights/org-team-insights/team-insights)
* Content Source: [Viva/insights/org-team-insights/team-insights.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/org-team-insights/team-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
