### ISSUE TITLE
Create Pop-out for Headspace Playlist

### ISSUE THREAD

**Issue by drinkswitch** [MicrosoftDocs/Viva#630]
The headspace playlists are great. However, a user can't multitask in Teams if they are listening to music in Teams. If the user clicks out of the playlist and goes somewhere else in Teams, the music stops playing. 😞

**Comment by scanum** [comment]
I know the product teams are always looking for user feedback and how to make SharePoint better. They keep a close tab on user feedback and it would be awesome if you could add your voice in User Voice 
SharePoint: https://sharepoint.uservoice.com/.
Skype for Business: https://www.skypefeedback.com/.
You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.
Thank you for your contribution to make the docs better! Much appreciated!
