### ISSUE TITLE
Allowed experience number without Viva Suite license.

### ISSUE THREAD

**Issue by mgoto-git** [MicrosoftDocs/Viva#635]
[Enter feedback here]

There are two statements about creating experience number without Viva Suite license.

First Note
------------
Users with a basic Microsoft 365 subscription (E license) **are limited to creating one experience**.
---------

https://learn.microsoft.com/en-us/viva/connections/set-up-admin-center#add-a-sharepoint-home-site-after-setting-up-a-connections-experience
-------------
Organizations that are not Viva Suite subscribers are limited to creating **three** Viva Connections experiences.
------------

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Version Independent ID: e6372fd8-9b87-2e82-a884-3a9220537882
* Content: [Set up Viva Connections in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/viva/connections/set-up-admin-center)
* Content Source: [Viva/connections/set-up-admin-center.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/connections/set-up-admin-center.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @AtkinE
* Microsoft Alias: **evanatkin**

**Comment by get-itips** [comment]
Hello @mgoto-git thanks for your feedback!
Corrected in https://github.com/MicrosoftDocs/Viva/commit/e631bd8dfd78831248fc1fd09786dd404499cfc4
