### ISSUE TITLE
Microsoft Teams mobile Viva cards logo SVG file getting zoomed showing only half logo

### ISSUE THREAD

**Issue by harshkumardubey** [MicrosoftDocs/Viva#636]
Microsoft Teams mobile Viva cards logo SVG file getting zoomed showing only half logo
Please check this gitHub issue.

https://github.com/OfficeDev/office-js/issues/3483

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ccca9392-e576-ef1f-79f5-f591810db155
* Version Independent ID: ccca9392-e576-ef1f-79f5-f591810db155
* Content: [Overview: Viva Connections](https://learn.microsoft.com/en-us/viva/connections/viva-connections-overview)
* Content Source: [Viva/connections/viva-connections-overview.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/connections/viva-connections-overview.md)
* Service: **viva**
* Sub-service: **viva-connections**
* GitHub Login: @AtkinE
* Microsoft Alias: **evanatkin**

**Comment by get-itips** [comment]
Hello @harshkumardubey how are you?

Here we are limited to **Documentation** issues and fixes.

Thank you,

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Maniac1488ss** [comment]
> 8
