### ISSUE TITLE
Update to reflect looping instruction on which portal manages viva app  365 settings or teams apps

### ISSUE THREAD

**Issue by MikeBakerSAV** [MicrosoftDocs/Viva#638]
the following section is actually a loop
https://learn.microsoft.com/en-us/viva/learning/configure-successfactors-content-source#admin-center-configuration
in actuality:

- microsoft 365 settings portal says use Teams apps to configure
- Teams apps portal says use microsoft 365 settings portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ab41cdf-5d70-8d9c-1899-31d971b0e582
* Version Independent ID: 5ab41cdf-5d70-8d9c-1899-31d971b0e582
* Content: [Configure SAP SuccessFactors as a content source for Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/configure-successfactors-content-source)
* Content Source: [Viva/learning/configure-successfactors-content-source.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/configure-successfactors-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Hello @MikeBakerSAV Mike, how are you?
I see your point as I could verify, however, it's more on 365 side than Docs/Learn, I'll see how can I pass this on reporting this.
Thanks for your feedback!

**Comment by get-itips** [comment]
I managed to report this to the team, closing.
