### ISSUE TITLE
Wrong link for Viva Goals homepage

### ISSUE THREAD

**Issue by Gonetak** [MicrosoftDocs/Viva#639]
The link that is supposed to take you to the viva goals homepage actually takes you to viva topics instead

**Comment by scanum** [comment]
Hi @Gonetak hope all is going well. Could you please help us by linking the article you are referring to? Thanks!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
