### ISSUE TITLE
Changing Working days and hour

### ISSUE THREAD

**Issue by pratikbhusal18** [MicrosoftDocs/Viva#646]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

It seems like there isn't way to change default working days and hours as documented here.
 https://learn.microsoft.com/en-us/viva/insights/advanced/reference/glossary
Your admin can change the default working days and hours in
Analyst settings > System defaults

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8504630e-00b3-e533-2046-d25cc22f34c4
* Version Independent ID: 8504630e-00b3-e533-2046-d25cc22f34c4
* Content: [Viva Insights advanced insights glossary](https://review.learn.microsoft.com/en-us/viva/insights/advanced/reference/glossary?source=docs)
* Content Source: [Viva/insights/advanced/reference/glossary.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/reference/glossary.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by tiburd** [comment]
The documentation team confirms that the glossary has been updated to reflect that "working hours" reflects concurrency with user Outlook settings.

Closing this issue.

cc: @get-itips @scanum
