### ISSUE TITLE
MIcrosoft Goals - Linking to Excel

### ISSUE THREAD

**Issue by tradersammy** [MicrosoftDocs/Viva#647]
[Enter feedback here]
Hi, concerning this page.  It's unclear how to connect an actual excel worksheet to your Goal Key Results - it explains making a "connection", but from there it's a bit fuzzy about how to get to the actual worksheet - what worksheet?  where is it stored (on your pc, or in the cloud?  This page doesn't display any images of actually selecting the worksheet.

I get an error "we're having trouble establishing a connection"

Thanks, Sam

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1ac6e8f-16f6-48c6-63d8-8ba2457dec38
* Version Independent ID: b1ac6e8f-16f6-48c6-63d8-8ba2457dec38
* Content: [Excel Online Integration](https://learn.microsoft.com/en-us/viva/goals/excel-online-integration#how-to-configure-the-excel-online-connection)
* Content Source: [Viva/goals/excel-online-integration.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/goals/excel-online-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by get-itips** [comment]
Hello @tradersammy 
How are you?
Is this step not working for you?

> Select a connection and a Workbook. As soon as you select the workbook, the associated sheets will be displayed in the Sheet dropdown menu. Select a worksheet.

Thanks,

**Comment by tradersammy** [comment]
Hi Andres,

Yes, I know how its supposed to work.   But it doesn’t.  I demonstrated to MS support and they are now working on the problem.

Cheers, Sam

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by get-itips** [comment]
Thanks for returning and sharing information,
I think the best would be then to continue with support, as here we are limited to documentation issues and fixes.
Thank you!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
