### ISSUE TITLE
Viva Connections Stats per user

### ISSUE THREAD

**Issue by JorgeSanchezGNV** [MicrosoftDocs/Viva#648]
Hi, 

I would like to know if with the Feature ID: 124918 in Viva Connections, Individual stats and use reports are going to be available for Viva Connections tracking.

If not, is there any possibility to develop something related? Our aim is to be able to track which features are being used or visited by the users in the Viva connections dashboard. 

Thanks in advance. 

![image](https://github.com/MicrosoftDocs/Viva/assets/122619020/9791588a-9b9a-44b5-afc1-9d1bf3a129ed)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
