### ISSUE TITLE
Update incorrect guidance on Global Admin requirements

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#649]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Submitting on behalf of one of our FastTrack Viva SMEs (@deancron). 

The "Access the Native Mode Alignment Tool" section of the native mode step-by-step documentation is incorrect in stating that whoever runs it needs to be a global admin:

https://learn.microsoft.com/en-us/viva/engage/native-mode-guide#2-access-the-native-mode-alignment-tool

A few months ago, engineering made changes that allows this to also be accessed/run by a user with the Yammer Administrator Azure AD account. Additionally, the 'important note' in there states that elevation (PIM) must be maintained the entire time the tool is running, which is also no longer the case. While this may seem like a small change to the docs, support is telling customers this as well, creating issues for us as we're trying to explain that both things are wrong, and that the customer only needs to use an account with the Yammer Administrator role assigned, and only needs to be elevated to that when:

- Starting alignment report generation
- Starting native mode migration
- Checking status of migration
- After migration finishes when/if they need to download an error report

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dad8c67-56da-d338-a5c2-2d3e5d46e75a
* Version Independent ID: 2dad8c67-56da-d338-a5c2-2d3e5d46e75a
* Content: [Viva Engage Native Mode: Step-by-step guide](https://review.learn.microsoft.com/en-us/viva/engage/native-mode-guide?branch=main#2-access-the-native-mode-alignment-tool)
* Content Source: [Viva/engage/native-mode-guide.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/native-mode-guide.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @Starshine89
* Microsoft Alias: **v-bvrana**

**Comment by get-itips** [comment]
Hello @soyalejolopez I'm working on this.

**Comment by Starshine89** [comment]
Submitted PR to fix the Native Mode guide to state that both Viva Engage admins can also use the alignment too.
https://github.com/MicrosoftDocs/Viva-pr/pull/5942

Thanks to @soyalejolopez and @DeanCron in Fast Track for catching this!
https://github.com/MicrosoftDocs/Viva/issues/649

**Comment by saashby** [comment]
Hello - When will this change go live please? Had two customers complain the MS Docs article still incorrectly states a Global Admin role is required. It also doesn't mention that PIM doesn't impact the native mode process after it is started

**Comment by get-itips** [comment]
@saashby 

the article was updated in August 10

> Use of the Native Mode Alignment Tool is limited to the Engage admin role and the Microsoft 365 Global Administrator role.

**Comment by tiburd** [comment]
@get-itips 
Thanks for resolving this issue!

cc: @scanum

**Comment by saashby** [comment]
Yeah it's still not accurate though, there are references in different places, like this text "The account that runs the Alignment Tool must maintain global admin status during the alignment process." 

Also I can't see that we mention PIM anywhere, this was the customers complaint as well, we should be calling out that Privileged Identity Manager does not impact the process as well. Alejandro added PIM in his original requested document update, but I can't see that the change was considered for the article?
