### ISSUE TITLE
Include note that the Pulse Admin needs to be licensed in order to configure Pulse

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#650]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Include note that the Pulse Admin needs to be licensed with Viva Pulse (Viva Suite) in order to access the admin settings (configure) Pulse. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e58f2f7d-7184-ccf3-a2ca-2bbee2b1832d
* Version Independent ID: e58f2f7d-7184-ccf3-a2ca-2bbee2b1832d
* Content: [Introduction to Microsoft Viva Pulse](https://review.learn.microsoft.com/en-us/viva/pulse/introduction-to-viva-pulse?branch=main#viva-pulse-admin)
* Content Source: [Viva/pulse/introduction-to-viva-pulse.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/pulse/introduction-to-viva-pulse.md)
* Service: **viva**
* Sub-service: **viva-pulse**
* GitHub Login: @michellehu-msft
* Microsoft Alias: **michellehu**

**Comment by get-itips** [comment]
Information added in https://github.com/MicrosoftDocs/Viva/commit/03c6e0b0034f6926b426afb0a6b267bc3a73f7d1

Thank you!
