### ISSUE TITLE
Given some of the native mode migration challenges, best to remove the "prioritization" note

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#651]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

This note makes it apparent that customers can request to prioritize getting Answers, including Native Mode migration, however, because of the challenges with current native mode migrations, it's probably best to remove this note until the pipeline / queue clears up a bit and avoid exacerbating the issue. 

`Interested tenants can request to get Answers enablement prioritized, which may include Native Mode Support or Viva Engage Topics Migration to Viva Topics. To do so, they can contact their customer account manager/Microsoft support staff for Viva Engage and file a support ticket. Microsoft reviews and processes these requests.`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e10035d8-6c44-53cf-560c-e2301cdd7ad1
* Version Independent ID: e10035d8-6c44-53cf-560c-e2301cdd7ad1
* Content: [Overview and setup of Answers in Viva](https://review.learn.microsoft.com/en-us/viva/engage/eac-answers-overview-set-up?branch=main)
* Content Source: [Viva/engage/eac-answers-overview-set-up.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/eac-answers-overview-set-up.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @Starshine89
* Microsoft Alias: **v-bvrana**

**Comment by get-itips** [comment]
Sentence was modified by @Starshine89 after this issue was created https://github.com/MicrosoftDocs/Viva/commit/bb6238e06ac990f06e7fca4a748b8e85986e2055

Thanks you,
