### ISSUE TITLE
Language Table Should Be Localized

### ISSUE THREAD

**Issue by jpalarchio** [MicrosoftDocs/Viva#654]
This table of languages is very difficult to read as it lists the language in the actual language itself as opposed to listing it in the local language for the page.

As an example, I can't tell if Mandarin is supported as I would need to know how to translate Mandarin into Mandarin to check.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b80d884-1a88-d2d2-0495-ae89c9ef5fef
* Version Independent ID: 1b80d884-1a88-d2d2-0495-ae89c9ef5fef
* Content: [Supported languages in Viva Learning](https://learn.microsoft.com/en-us/viva/learning/viva-learning-supported-languages)
* Content Source: [Viva/learning/viva-learning-supported-languages.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/viva-learning-supported-languages.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Hello @jpalarchio Joe, how are you?
Just FYI I'm discussing this internally.

**Comment by bhaswatic** [comment]
Closed and discussing internally with Product Group input.
