### ISSUE TITLE
Delete Option is not available

### ISSUE THREAD

**Issue by ahamin01** [MicrosoftDocs/Viva#655]
Hello,

It's mentioned under this section "Set whether to retain deleted messages and files stored in Viva Engage" that we can select Delete option when it's needed to delete the data permenantly. However, there's no Delete option under Governance and Compliance > Data Export. Could you please check this, or add an explanatory screenshot?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bac01d2-753e-6b10-96c8-70cc818ae945
* Version Independent ID: 6bac01d2-753e-6b10-96c8-70cc818ae945
* Content: [Manage Viva Engage data compliance](https://learn.microsoft.com/en-us/viva/engage/manage-security-and-compliance/manage-data-compliance)
* Content Source: [Viva/engage/manage-security-and-compliance/manage-data-compliance.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/manage-security-and-compliance/manage-data-compliance.md)
* Service: **viva**
* GitHub Login: @cedemaagd
* Microsoft Alias: **v-cdemaagd**

**Comment by get-itips** [comment]
Article has been corrected.
Thanks for your feedback!
