### ISSUE TITLE
More detail needed for the "Reserved Optional" section of this page

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/Viva#661]
Hey team - can we please update this page for the Required and Reserved fields.  I had a customer comment today that it was super confusing and there should be an indication of which PowerBI templats the "reserved" fields might be assocatiated with so that they could make an informed decision about what fields to gather data on for the CSV upload file.

For example -

Reserved optional
The following attributes are reserved column headers for attributes that are currently used to calculate, filter, and group data.
...
...
HourlyRate - used in Impact Explorere / Meeting Effectiveness / Recurring Meeting Audit
...
...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee20f56-ff3e-9d5d-29bd-f6a86e537a1c
* Version Independent ID: 5ee20f56-ff3e-9d5d-29bd-f6a86e537a1c
* Content: [Prepare organizational data in Viva Insights](https://learn.microsoft.com/en-us/viva/insights/advanced/admin/prepare-org-data)
* Content Source: [Viva/insights/advanced/admin/prepare-org-data.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/admin/prepare-org-data.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by get-itips** [comment]
Content has been updated to address the feedback. Thanks
