### ISSUE TITLE
Viva Topics 1st party app from Microsoft is available

### ISSUE THREAD

**Issue by sinansuer** [MicrosoftDocs/Viva#664]
Viva Topics 1st party app is now available in the Microsoft Teams Apps repository:
https://admin.teams.microsoft.com/policies/manage-apps/0050a1a5-5a58-40ea-a3af-ca6223a88cb4
Using PowerShell to create an app package for Topics, and uploading the package is no longer required.
This documentation needs to be updated to reflect the changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad2452fb-b5a4-8d84-d7b8-e6c890423c84
* Version Independent ID: ad2452fb-b5a4-8d84-d7b8-e6c890423c84
* Content: [Add the Viva Topics app in the Teams Admin Center](https://learn.microsoft.com/en-us/viva/topics/add-topics-app?source=docs)
* Content Source: [Viva/topics/add-topics-app.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/topics/add-topics-app.md)
* Service: **viva**
* Sub-service: **viva-topics**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by daisyfell** [comment]
thanks @sinansuer , update should go live by late afternoon US pacific time
