### ISSUE TITLE
404 error when accessing link "error codes section of the troubleshoot native mode article. "

### ISSUE THREAD

**Issue by jillianknight** [MicrosoftDocs/Viva#665]
Broken link on this text: [error codes section of the troubleshoot native mode article](https://learn.microsoft.com/en-us/Viva/engage/troubleshoot-native-mode.md#error-codes).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2dad8c67-56da-d338-a5c2-2d3e5d46e75a
* Version Independent ID: 2dad8c67-56da-d338-a5c2-2d3e5d46e75a
* Content: [Viva Engage Native Mode: Step-by-step guide](https://learn.microsoft.com/en-us/viva/engage/native-mode-guide?source=recommendations)
* Content Source: [Viva/engage/native-mode-guide.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/native-mode-guide.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @Starshine89
* Microsoft Alias: **v-bvrana**

**Comment by get-itips** [comment]
Hello thanks for your feedback, it was fixed in https://github.com/MicrosoftDocs/Viva/commit/f19a1b44bfdbfc9fabd59011b8dc48c6b8cb1aa7
