### ISSUE TITLE
Typo error in the note section

### ISSUE THREAD

**Issue by IpsitoDutta** [MicrosoftDocs/Viva#666]
Under the section: https://learn.microsoft.com/en-us/viva/engage/eac-as-access-eac#configure-your-tenant

please correct the typo: "Because Viva Engage is power by Yammer technology...." to "Because Viva Engage is powered by Yammer technology".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a3a65b18-c42d-9db4-f895-26119c68c2e6
* Version Independent ID: a3a65b18-c42d-9db4-f895-26119c68c2e6
* Content: [Access the Viva Engage admin center](https://learn.microsoft.com/en-us/viva/engage/eac-as-access-eac)
* Content Source: [Viva/engage/eac-as-access-eac.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/eac-as-access-eac.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @Starshine89
* Microsoft Alias: **mamiejohnson**

**Comment by get-itips** [comment]
Thanks for your feedback, it was fixed in https://github.com/MicrosoftDocs/Viva/commit/9d0338ef1a6acff567621c5f88bb79c0cf685883
