### ISSUE TITLE
Viva Goals Solutions Partner Training

### ISSUE THREAD

**Issue by Brettpm2** [MicrosoftDocs/Viva#667]
The training to become a Modern Work Solutions Partner is great - but does not relate at all to the skills necessary to set up and implement Viva Goals.

Since Viva Goals can be a stand alone module, capabilities around Teams, Glint, Insight, etc. are of no use.

Without Viva Goals specific training, I would expect most of the Viva Goals pilots will fail, Sales Reps will have difficulty finding Partners that are capable, and the Reps will not achieve their sales targets.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
