### ISSUE TITLE
Support for Dutch language model

### ISSUE THREAD

**Issue by Qars** [MicrosoftDocs/Viva#675]
For processing topics and indexing content we are still waiting for the Dutch language model. Hopefully this will follow soon so Viva Topics can be used better in The Netherlands and Belgium.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Qars** [comment]
Why is this ticket closed, Microsoft does not yet support the Dutch language for processing topics? Or do I miss something? See second table on this page https://learn.microsoft.com/en-us/viva/topics/topics-language-support
