### ISSUE TITLE
Vivi insights outlook add-in always changes Outlook reading pane position to bottom.

### ISSUE THREAD

**Issue by stoo101** [MicrosoftDocs/Viva#678]
There's a better write-up over here: https://answers.microsoft.com/en-us/outlook_com/forum/all/viva-insights-add-in-for-outlook-changes-mail/73fbed2e-5e20-4fbd-8158-aa1c4ec5f137

But essentially the outlook add-in is messing with my reading pane layout position when I swap from calendar view to mail view.

**Comment by stoo101** [comment]
I'd logged this in wrong place

**Comment by stoo101** [comment]
I may not have opened this in the wrong place after all?

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
