### ISSUE TITLE
G5 license 

### ISSUE THREAD

**Issue by arianVITA** [MicrosoftDocs/Viva#686]
Does the G5 license include all of the Viva Insights features? We are currently mapping out all of the features that we could potentially use within the license without any additional purchases.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd37101-d514-2d0d-f3bf-863eb4a39a2e
* Version Independent ID: d3b5f633-8fc4-df86-1878-808acbb9c3ae
* Content: [Introduction to Viva Insights](https://learn.microsoft.com/en-us/viva/insights/introduction)
* Content Source: [Viva/insights/introduction.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/introduction.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
