### ISSUE TITLE
Virginia IT Agency

### ISSUE THREAD

**Issue by arianVITA** [MicrosoftDocs/Viva#687]
Does an organization with a G5 license have access to all Microsoft Learning features listed on this page, without purchasing any additional Viva Suite or other Viva plans?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a43718f-7587-8b98-10fe-07dbbfda8ffe
* Version Independent ID: 1a43718f-7587-8b98-10fe-07dbbfda8ffe
* Content: [Overview of Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/overview-viva-learning)
* Content Source: [Viva/learning/overview-viva-learning.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/overview-viva-learning.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
