### ISSUE TITLE
Viva Connections Dashboard Webpart: Upgrade Request

### ISSUE THREAD

**Issue by KristaEwingHumana** [MicrosoftDocs/Viva#693]
Right now, our normal users (50,000+) do not have the ability to hide or rearrange their Viva Connections Dashboard cards on their webpart. We're getting requests that, like other tools they have, they're able to customize how their dashboard functions for them. Microsoft - could you please consider allowing admins to enable any card we deem to be hide-able, or rearranged by users? Some cards may need to be showing per-company policy, but others could be re-arranged or hidden.
Thanks

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
