### ISSUE TITLE
Content Sources links are not working

### ISSUE THREAD

**Issue by praveenpudi329** [MicrosoftDocs/Viva#695]
Content Sources related links are redirecting to Viva Topics manage page, where I cant see anything related to content sources

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 674f1146-b9b1-0183-0770-5fe626161949
* Version Independent ID: 674f1146-b9b1-0183-0770-5fe626161949
* Content: [Analytics for Microsoft Viva Topics](https://learn.microsoft.com/en-us/viva/topics/topics-analytics?source=docs)
* Content Source: [Viva/topics/topics-analytics.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/topics/topics-analytics.md)
* Service: **viva**
* GitHub Login: @daisyfell
* Microsoft Alias: **daisyfeller**

**Comment by get-itips** [comment]
Article was updated. Thank you!
