### ISSUE TITLE
Vivi insight Mindfulness is not working

### ISSUE THREAD

**Issue by CatrinGu** [MicrosoftDocs/Viva#696]
I get error
"we are sorry we ran into an issue"
this has been there for weeks
![image](https://github.com/MicrosoftDocs/Viva/assets/145319305/012f66dc-41b6-406e-b509-e7624ab4d018)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
