### ISSUE TITLE
Viva goals doesn't attach excel spreadsheet

### ISSUE THREAD

**Issue by rwalker-barenbrug** [MicrosoftDocs/Viva#708]
[Enter feedback here]
I'm trying to get Viva Goals to get a check-in from excel. I've enabled excel integration. I try add spreadsheet but it fails when I try set goal progress to "Connect data source to auto-update progress" - this field doesn't appear ina Goal but does in a Key Obljective. The field doesn't populate with the name of my Excel integtation and thus doesn't ask for worksheet name (or cell).

Thanks, Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b1ac6e8f-16f6-48c6-63d8-8ba2457dec38
* Version Independent ID: b1ac6e8f-16f6-48c6-63d8-8ba2457dec38
* Content: [Excel Online Integration](https://learn.microsoft.com/en-us/viva/goals/excel-online-integration)
* Content Source: [Viva/goals/excel-online-integration.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/goals/excel-online-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
