### ISSUE TITLE
Please validate the PowerShell

### ISSUE THREAD

**Issue by Jmartinez589** [MicrosoftDocs/Viva#712]
I am reviewing the article and attempting the commands.

Set-DefaultTenantMyAnalyticsFeatureConfig -PrivacyMode <opt-in/opt-out>`

It appears that there is 'PrivacyMode' perhaps this has changed. If so, please update the article by removing this reference to 'PrivacyMode'

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c73d7596-cba2-d593-ec69-9ec26b8c4eb8
* Version Independent ID: c73d7596-cba2-d593-ec69-9ec26b8c4eb8
* Content: [Configure personal insights defaults](https://learn.microsoft.com/en-us/viva/insights/advanced/setup-maint/configure-personal-insights)
* Content Source: [Viva/insights/advanced/setup-maint/configure-personal-insights.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/setup-maint/configure-personal-insights.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @lilyolason
* Microsoft Alias: **v-lilyolason**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
