### ISSUE TITLE
Wrong link to document

### ISSUE THREAD

**Issue by urban-karolis** [MicrosoftDocs/Viva#721]
Link to [export log file](https://learn.microsoft.com/en-us/viva/learning/use-tabs?view=o365-worldwide#managing-providers&preserve-view=true)  document in [Multi-Geo}(https://learn.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source#multi-geo) section leads to  wrong documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Version Independent ID: 3055d301-6a49-ab29-5fd0-2bdf1b4076d6
* Content: [Add SharePoint as a learning content source for Microsoft Viva Learning](https://learn.microsoft.com/en-us/viva/learning/configure-sharepoint-content-source)
* Content Source: [Viva/learning/configure-sharepoint-content-source.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/configure-sharepoint-content-source.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Hello @urban-karolis thanks, I'm working on this
