### ISSUE TITLE
the same sentences repeated

### ISSUE THREAD

**Issue by devpowerplatform** [MicrosoftDocs/Viva#738]
[Enter feedback here]

the park below 
"With Viva Glint, you have the platform to capture the broadest set of direct and indirect signals and leverage next-generation AI to recommend actions to improve engagement and business performance. Viva Glint helps connect the dots from insight to action and offer recommendations based on feedback from Viva Glint surveys." 

is repeated twice. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9be62a69-8153-f3e1-fc52-888dff432900
* Version Independent ID: 9be62a69-8153-f3e1-fc52-888dff432900
* Content: [Support productivity and wellbeing with actionable insights](https://learn.microsoft.com/en-us/viva/experience-insight)
* Content Source: [Viva/experience-insight.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/experience-insight.md)
* Service: **viva**
* GitHub Login: @LoreenLa
* Microsoft Alias: **loreenl**

**Comment by get-itips** [comment]
fixed in https://github.com/MicrosoftDocs/Viva/commit/e785d552c7bbaca2d06693b8ae495dfec2809cfd

thank you
