### ISSUE TITLE
What licenses are needed to create vs view campaigns

### ISSUE THREAD

**Issue by karleesm** [MicrosoftDocs/Viva#754]
[Can we please include something about what licenses are needed to run and to participate in a campaign.  I get asked many questions about thinking just one Engage premium license is required to create the campaign.  It would be helpful to direct people to this.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
* Version Independent ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
* Content: [Manage and set up campaigns in Microsoft Viva Engage](https://learn.microsoft.com/en-us/viva/engage/campaigns)
* Content Source: [Viva/engage/campaigns.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/campaigns.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @Starshine89
* Microsoft Alias: **v-bvrana**

**Comment by get-itips** [comment]
Hello, I'm checking this

**Comment by get-itips** [comment]
Hello @karleesm 
I could get information that Viva Engage premium is required to run or participate in a campaign
