### ISSUE TITLE
I can't post content on viva engage, help

### ISSUE THREAD

**Issue by QuocCuong1997** [MicrosoftDocs/Viva#756]
![Screenshot_2](https://github.com/MicrosoftDocs/Viva/assets/129703240/811fd143-5e8e-4885-87a0-0b48ba85aec1)

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
