### ISSUE TITLE
Include note to leave ManagerID blank for CEOs

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#762]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Current guidance says that all required fields, such as ManagerID, need to have non-blank values. The CEO will not have a manager.
We should include a comment in the table for "ManagerID" that for CEOs this can be left blank.  The validation threshold for this field is 95% instead of 100% to account for these scenarios. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ee20f56-ff3e-9d5d-29bd-f6a86e537a1c
* Version Independent ID: 5ee20f56-ff3e-9d5d-29bd-f6a86e537a1c
* Content: [Prepare organizational data in Viva Insights](https://review.learn.microsoft.com/en-us/viva/insights/advanced/admin/prepare-org-data)
* Content Source: [Viva/insights/advanced/admin/prepare-org-data.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/advanced/admin/prepare-org-data.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @zachminers
* Microsoft Alias: **v-zachminers**

**Comment by zachminers** [comment]
Thank you for the feedback. The doc has been updated to incorporate this feedback, so we can close this ticket now.

https://learn.microsoft.com/en-us/viva/insights/advanced/admin/prepare-org-data#attribute-reference
