### ISSUE TITLE
B2B Guests supported in EU GEO?

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/Viva#766]
Hi, this article states that B2B Guests (and external access) are not supported in EU GEO. But the article https://learn.microsoft.com/en-us/viva/engage/get-started-with-viva-engage/azure-ad-b2b-guests-viva-engage mentioning in FAQ states that this is supported in EU GEO. Can you please clarify, which is true or what type of external access is supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ae39c9a-4553-1804-76fa-eedd9125cca9
* Version Independent ID: 2ae39c9a-4553-1804-76fa-eedd9125cca9
* Content: [Data residency for Viva Engage](https://learn.microsoft.com/en-us/viva/engage/manage-security-and-compliance/data-residency)
* Content Source: [Viva/engage/manage-security-and-compliance/data-residency.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/manage-security-and-compliance/data-residency.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @cedemaagd
* Microsoft Alias: **v-cdemaagd**

**Comment by Starshine89** [comment]
Hi Petr,
The two articles you cite are referring to two different things. 

- External networks are not supported in EU. 
- B2B guests are supported in EU.

**Data residency for Viva Engage** refers to external networks for collaboration, NOT communities, which do allow external guests. 

**Work with AzureAD-B2B guests in Viva Engage communities** is referring to communities, which allow external guests   and is supported in EU.
 
I hope this clarifies the issue!
Barbara Vrana

**Comment by Kazzan** [comment]
Hi, thanks for clarification. So, you can add these terms to which such refers to article itself?

Because words like "The following Viva Engage features are not available" followed by "All external collaboration features" and "All external collaboration features".

So, as I understand, I can add B2B Guest to Community inside Viva Engage but cannot add him to "Viva Engage tenant as whole". So why, because in Native Mode all the communities are the same Microsoft 365 Groups, even the "All Company"?
