### ISSUE TITLE
No Support for Graveyard Shift

### ISSUE THREAD

**Issue by wh0-a** [MicrosoftDocs/Viva#767]
When editing the work week schedule, it appears there’s no way to input a shift that starts in the PM and ends after midnight.
¯\_(ツ)_/¯
I hope that helps!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
