### ISSUE TITLE
Mail Enabled Security Groups are now supported

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#779]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Mail enabled security groups are supported for permissions, not just M365 Groups. See here: 

https://www.microsoft.com/microsoft-365/roadmap?featureid=118675

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db22de2a-0ec5-d71b-96f6-617585e0489b
* Version Independent ID: db22de2a-0ec5-d71b-96f6-617585e0489b
* Content: [Use Microsoft 365 Groups permissions with SharePoint content in Viva Learning](https://review.learn.microsoft.com/en-gb/viva/learning/sharepoint-permissions?view=o365-worldwide&branch=main)
* Content Source: [Viva/learning/sharepoint-permissions.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/learning/sharepoint-permissions.md)
* Service: **viva**
* Sub-service: **viva-learning**
* GitHub Login: @bhaswatic
* Microsoft Alias: **bhaswatic**

**Comment by get-itips** [comment]
Thanks for your feedback
