### ISSUE TITLE
Change the Email Delivery time to coincide with Viva settings

### ISSUE THREAD

**Issue by chaosrecords** [MicrosoftDocs/Viva#788]
It is a little counterproductive when you set your working times and time zones to 8am to 5pm in Viva settings, but the email weekly report is sent at 4:00AM effectively waking me up. 

Outlook has options to send emails during business hours. Yes im aware i can create quiet times in Outlook but how about an option for Viva to deliver you your weekly digest during your business hours only or a specific time ? 

Just a thought.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
