### ISSUE TITLE
Confirmation - Is Viva Pulse Administrator Group available under Intune tabs to view the admin roles available for your organization?

### ISSUE THREAD

**Issue by PrasadKasireddy** [MicrosoftDocs/Viva#793]
Please confirm - Is Viva Pulse Administrator Group available under **Intune tabs** to view the admin roles available for your organization?

<img width="689" alt="Viva_Pulse" src="https://github.com/MicrosoftDocs/Viva/assets/11626905/1e87aa9c-077c-43f4-9f7d-de66048d9560">
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d86605a1-ebf7-bf0d-3570-68a3ec9f4c4a
* Version Independent ID: d86605a1-ebf7-bf0d-3570-68a3ec9f4c4a
* Content: [Assign a Viva Pulse admin in the Microsoft 365 admin center](https://learn.microsoft.com/en-us/viva/pulse/setup-admin-access/assign-a-viva-pulse-admin-in-m365-admin-center)
* Content Source: [Viva/pulse/setup-admin-access/assign-a-viva-pulse-admin-in-m365-admin-center.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/pulse/setup-admin-access/assign-a-viva-pulse-admin-in-m365-admin-center.md)
* Service: **viva**
* Sub-service: **viva-pulse**
* GitHub Login: @michellehu-msft
* Microsoft Alias: **michellehu**

**Comment by michellehu-msft** [comment]
@PrasadKasireddy Thank you for calling this out. Viva Pulse admin roles can only be viewed in the Microsoft Entra ID tab in the Microsoft Admin Center. I will update our technical documentation.

**Comment by get-itips** [comment]
Thanks @michellehu-msft 
Updated in https://github.com/MicrosoftDocs/Viva/commit/e32b19923670a9a45d55a1d42213bf3a634bec24
