### ISSUE TITLE
Include Viva Topics Viva/index.yml

### ISSUE THREAD

**Issue by PrasadKasireddy** [MicrosoftDocs/Viva#794]
Viva Topics should be part of learning & knowledge management which is missed, please include Viva Topics 

"Help your workforce learn, grow, and succeed with Viva Learning,**Viva Topics**."

<img width="929" alt="Viva_Topics" src="https://github.com/MicrosoftDocs/Viva/assets/11626905/fc0dfeeb-a369-45f0-85bf-2b65179f9eaa">

**Comment by get-itips** [comment]
Hello @PrasadKasireddy how are you?
I don't fully understand your request, can you please explain where you want to include that article?
Thanks

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
