### ISSUE TITLE
"Features not available for Viva Engage tenants in the EU Geo" section is misleading

### ISSUE THREAD

**Issue by sinansuer** [MicrosoftDocs/Viva#802]
The external collaboration restrictions referred in the article leads readers to believe that EU Geo does not support any external collaboration capabilities.
This is not correct.
Azure B2B Guest experience is available EU Geo for external collaboration purposes.
It is possible to invite guests into Viva Engage Communities using Azure AD B2B:
Reference articles:
[Work with AzureAD-B2B guests in Viva Engage communities | Microsoft Learn](https://learn.microsoft.com/en-us/viva/engage/get-started-with-viva-engage/azure-ad-b2b-guests-viva-engage)
[Collaborate with guests in a Viva Engage community | Microsoft Learn](https://learn.microsoft.com/en-us/viva/engage/work-with-external-users/collaborate-guests-external-viva-engage-community)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ae39c9a-4553-1804-76fa-eedd9125cca9
* Version Independent ID: 2ae39c9a-4553-1804-76fa-eedd9125cca9
* Content: [Data residency for Viva Engage](https://learn.microsoft.com/en-us/viva/engage/manage-security-and-compliance/data-residency)
* Content Source: [Viva/engage/manage-security-and-compliance/data-residency.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/engage/manage-security-and-compliance/data-residency.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @cedemaagd
* Microsoft Alias: **dmillerdyson**

**Comment by get-itips** [comment]
Hello @sinansuer 
I am checking this, thanks

**Comment by get-itips** [comment]
Hello @sinansuer An update to the article should be reflected in the published version of the article soon. cc @tiburd 

Thank you.
