### ISSUE TITLE
Closed Caption SharePoint content

### ISSUE THREAD

**Issue by Charles8430** [MicrosoftDocs/Viva#823]
When .mp4's that contain cc tracks are added to the SharePoint Learning Content Repository, the cc option does not appear.
However, LinkedIn Learning content does show the cc option.

What is the correct procedure for adding and showing cc data to SharePoint Learning Content videos?

Thanks,

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
