### ISSUE TITLE
licensing requirement unclear

### ISSUE THREAD

**Issue by LennartaeHoefer** [MicrosoftDocs/Viva#830]
_The following user-level configuration can only be modified when users have P1 licenses enabled for Viva Insights._

I cannot find any information about P1 licenses. Is this related to a Viva license? There is a Microsoft Entra ID P1 license - but how would that relate to this setting? Please put in the specific name of the license otherwise it is confusing. 

It would also help to state if the "user" is the person running the script (admin) or the user accounts which is targeted is meant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5062d99-7d49-3a2f-7c28-304abf7b940f
* Version Independent ID: fa2f2c5a-116f-6870-52dd-fdc691248160
* Content: [Admin tasks for the Viva Insights app](https://learn.microsoft.com/en-us/viva/insights/personal/teams/viva-teams-app-admin-tasks#user-level-configuration)
* Content Source: [Viva/insights/personal/teams/viva-teams-app-admin-tasks.md](https://github.com/MicrosoftDocs/viva/blob/public/Viva/insights/personal/teams/viva-teams-app-admin-tasks.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @zachminers
* Microsoft Alias: **v-zachminers**

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by zachminers** [comment]
Hello. Thank you for submitting this feedback! The content has been updated to address this feedback. You may close this ticket. Thank you.
