### ISSUE TITLE
Viva Goals Check-In Owner Update Tagging Bug

### ISSUE THREAD

**Issue by movableinkkyk** [MicrosoftDocs/Viva#833]
I was told this forum was the best way to report a bug. I use Viva Goals for my company and I'm having an issue tagging a new owner for the "Check-In Owner' field on a KR. You'll see my name is listed as a user, but when I try to search for it, it does not appear. This happens for any name. I'm unable to tag the right person because of the issue.

<img width="699" alt="Screenshot 2023-11-27 at 2 12 39 PM" src="https://github.com/MicrosoftDocs/Viva/assets/152219553/2d009796-c0d4-48b9-8d71-d4018dff96c1">
<img width="709" alt="Screenshot 2023-11-27 at 2 12 48 PM" src="https://github.com/MicrosoftDocs/Viva/assets/152219553/56fa5ec4-2907-493c-972d-ef16b2ac0502">

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
