### ISSUE TITLE
Use of uncertified visual 

### ISSUE THREAD

**Issue by kelleylong-m** [MicrosoftDocs/Viva#846]
This report is using an uncertified visual called "HTML Content". This might cause issue to user whose tenant has blocked user from viewing uncertified visual. Please consider mitigating the issue or update documentation to address this.

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.
